select cpe.entity_id as product_id,
       cpev.value as product_title,
       concat('https://www.kttape.com/',ur.request_path) as product_url,
       r.created_at as date,
       rd.detail as review_content,
       res.rating_summary as review_score,
       rd.title as review_title,
       rd.nickname as display_name,
       ce.email,
       'US' as md_customer_country
from catalog_product_entity cpe
inner join              catalog_product_entity_varchar  cpev  on cpe.row_id=cpev.row_id
inner join url_rewrite ur on cpe.entity_id=ur.entity_id and ur.entity_type='product'
inner join             review r on r.entity_pk_value=cpe.entity_id
inner join review_detail rd on r.review_id = rd.review_id
inner join review_store rs on r.review_id=rs.review_id
inner join review_entity_summary res on res.entity_pk_value=r.entity_pk_value
inner join rating_option_vote rov on r.review_id = rov.review_id
inner join rating_option_vote_aggregated rova on rova.entity_pk_value=r.entity_pk_value
inner join customer_entity ce on rd.customer_id = ce.entity_id
where cpev.attribute_id=73 and cpev.store_id=0;

select * from eav_attribute where attribute_id=73

select distinct
       cpe.entity_id as product_id,
       cpev.value as product_title,
       concat('https://www.kttape.com/',ur.request_path) as product_url,
       date(r.created_at) as date,
       rd.detail as review_content,
       res.rating_summary as review_score,
       rd.title as review_title,
       rd.nickname as display_name,
       ce.email,
       'US' as md_customer_country
from catalog_product_entity cpe
inner join              catalog_product_entity_varchar  cpev  on cpe.row_id=cpev.row_id
inner join url_rewrite ur on cpe.entity_id=ur.entity_id and ur.entity_type='product'
inner join             review r on r.entity_pk_value=cpe.entity_id
inner join review_detail rd on r.review_id = rd.review_id
inner join review_store rs on r.review_id=rs.review_id
inner join review_entity_summary res on res.entity_pk_value=r.entity_pk_value
inner join rating_option_vote rov on r.review_id = rov.review_id
inner join rating_option_vote_aggregated rova on rova.entity_pk_value=r.entity_pk_value
inner join customer_entity ce on rd.customer_id = ce.entity_id
where cpev.attribute_id=73 and res.rating_summary!=0
  -- and cpev.store_id=0
order by email, concat('https://www.kttape.com/',ur.request_path);

-- version 1 query for review : it has rating and email issues
# D:\m2\projects\noritake\csw\kttape_yotpo_reviews3.tsv
select
         distinct cpe.entity_id as product_id,
       tre.product as product_title,
        ( select concat('https://www.kttape.com/',ur.request_path) as product_url from url_rewrite ur where ur.entity_id=cpe.entity_id and ur.entity_type='product'  limit  1) as product_url,
        tre.created as date,
          rd.detail as review_content,
                        (select res.rating_summary from review_entity_summary res where res.rating_summary=tre.id limit 1) as review_score,
          tre.title as review_title,
          tre.nickname as display_name,
       (select ce.email from customer_entity ce where ce.entity_id = rd.customer_id limit 1) as email,
       'US' as md_customer_country
from temp_reviews_export tre
inner join review_detail rd on tre.id=rd.review_id
inner join catalog_product_entity cpe on tre.sku=cpe.sku
inner join              catalog_product_entity_varchar  cpev  on cpe.row_id=cpev.row_id  and cpev.attribute_id=73
left join review_entity_summary res on res.entity_pk_value=tre.id;
-- group by cpe.entity_id having count(cpe.entity_id)>1;

-- vresion 2 qeury : isme rating or score wale issue fixed hogae
select          distinct  r.review_id,          res.rating_summary as review_score,
                         tre.sku,
cpe.entity_id as product_id,
cpev.value as product_title ,
( select concat('https://www.kttape.com/',ur.request_path) as product_url from url_rewrite ur where ur.entity_id=cpe.entity_id and ur.entity_type='product'  limit  1) as product_url,
r.created_at as date2,
rd.detail as review_content,
(
    CASE
        WHEN (res.rating_summary=0)  THEN 0
        WHEN (res.rating_summary=38 or res.rating_summary=46 or res.rating_summary=60 or res.rating_summary=72 or res.rating_summary=73)  THEN 1
        WHEN (res.rating_summary=30)  THEN 2
        WHEN (res.rating_summary=82)  THEN 3
        WHEN (res.rating_summary=70 or res.rating_summary=80 or res.rating_summary=89 or res.rating_summary=95 or res.rating_summary=97)  THEN 4
        WHEN (res.rating_summary=74 or res.rating_summary=85 or res.rating_summary=86 or res.rating_summary=90 or res.rating_summary=93 or res.rating_summary=100)  THEN 5
    END
)   as review_score,
tre.title as review_title,
tre.nickname as display_name,
(select ce.email from customer_entity ce where ce.entity_id = rd.customer_id limit 1) as email,
'US' as md_customer_country
from temp_reviews_export tre
inner join review r on tre.id=r.review_id
inner join review_detail rd on r.review_id = rd.review_id
inner join review_entity_summary res on res.entity_pk_value=r.entity_pk_value
inner join catalog_product_entity cpe on tre.sku=cpe.sku
inner join              catalog_product_entity_varchar  cpev  on cpe.row_id=cpev.row_id  and cpev.attribute_id=73
where  rd.store_id=2 and res.store_id=2 and cpe.entity_id=19;
#   and cpe.entity_id=144
#   and r.review_id=28889
#
--  limit 5

-- ======== xxxxxxxxxxxxxxxxxxxxxx
/* CREATE TABLE */
# CREATE TABLE temp_reviews_export(
# id VARCHAR(100),
# created VARCHAR(100),
# status VARCHAR(100),
# title VARCHAR(100),
# nickname VARCHAR(100),
# review VARCHAR(100),
# visibility VARCHAR(100),
# type VARCHAR(100),
# product VARCHAR(100),
# sku VARCHAR(100)
# );


# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('36334','Aug 29, 2019, 11:03:45 AM','Approved','Very good hold!','Mizuno 29','I am a golf professional and this tape stays wh...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro Extreme Â®','KTEXTCONF0003');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('28893','Aug 14, 2019, 7:01:58 PM','Approved','Kt recovery','H Davenport','I love this stuff. Ive tried so many other dif...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Recovery+ Â® Pain Relief Gel Roll-On','10001559');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('28892','Aug 13, 2019, 2:33:54 PM','Approved','Almost Perfect','BJ','I have a rare autoimmune disease that causes de...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape ProÂ® Wide','10000644');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('28891','Aug 13, 2019, 12:37:59 PM','Approved','Tested it out... love it!','Hailey','Iâ€™ve had very bad knees since I was a kid but I...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Cotton Elastic Sports Tape','KTCTAPCOT0001');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('28889','Aug 9, 2019, 9:43:12 AM','Approved','Keeps me running','The Flash','I have knee pain, and this stuff works. I can ...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro Â®','KTCTAPPRO0001');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('28888','Aug 2, 2019, 11:37:50 AM','Approved','Great product!','Grace','This really does help ease pain. Would recommen...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Recovery+ Â® Pain Relief Gel Roll-On','10001559');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('28887','Aug 1, 2019, 1:08:51 PM','Approved','Awesome','Mel','I love this product. Thank you.','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape KT Flex Â®','10000383');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('28886','Jul 27, 2019, 12:44:58 PM','Approved','Magic in roll!','Gelcys','You guys hit it on the money! I suffer from lot...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Recovery+ Â® Pain Relief Gel Roll-On','10001559');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('28885','Jul 22, 2019, 5:24:53 PM','Approved','Best Tape Ever','Thientho','Thisâ€™ the best tape ever. I have a really bad a...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro Â®','KTCTAPPRO0001');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('28884','Jul 18, 2019, 10:09:07 AM','Approved','Stays on and supports','AnimalFlower','I have been using these and they not only give ...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape KT Flex Â®','10000383');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('28883','Jul 17, 2019, 8:06:36 AM','Approved','Fantastic','Mel','2 total knees same knee due to NICKLE allergy. ...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Recovery+ Recovery Patch Â®','10000381');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('28882','Jul 15, 2019, 10:29:58 PM','Approved','Wish they lasted longer','ChrisV','While I feel this tape does offer some relief, ...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro Â®','KTCTAPPRO0001');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('28847','May 30, 2019, 7:34:58 PM','Approved','Works great for pain','SpecialLadt','Been using the tape because I have osteoarthrit...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Recovery+ Recovery Patch Â®','10000381');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('28846','May 28, 2019, 6:54:51 PM','Approved','Great stuff','Dr Rob','I have stopped wearing a low back brace and wea...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape ProÂ® Wide','10000644');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('28843','May 10, 2019, 9:17:26 AM','Approved','Helps against blisters','Dave','After every half marathon I get painful blister...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Performance+ Â® Blister Prevention Tape','KTBLICONF0007');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('28841','May 7, 2019, 11:37:14 PM','Approved','Puts all other tapes to shame.','MaritDW','I tried the basic tape and liked it. I tried th...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro Extreme Â®','KTEXTCONF0003');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('28840','May 5, 2019, 1:29:23 PM','Approved','Poor Product','Deni44','This product is not stick properly especially b...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT TapeÂ® Gentle Tape','10001463');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('28839','May 2, 2019, 1:16:42 PM','Approved','Excellent Tape','Debbie','I regularly use KT Tape for full knee support (...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro Â®','KTCTAPPRO0001');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('28838','Apr 26, 2019, 8:50:05 PM','Approved','Great product...once its open','pickle jar','This thing is great! The option to switch from ...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Recovery+ Â® Ice/Heat Massage Ball','10001723');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('28837','Apr 25, 2019, 6:56:58 PM','Approved','Do not bother','Kisa','Ive been using Kt tape pro for the past few mo...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Customer','KT TapeÂ® Gentle Tape','10001463');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('28835','Apr 20, 2019, 9:18:47 PM','Approved','Removal caused scaring on my legs, skin removal...','Hannah','I have used this tape for years, that is until ...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro-X Â®','10000342');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('28834','Apr 19, 2019, 12:35:43 PM','Approved','Golfers elbow','NateDogg','I was a total skeptic before Using Pro Extreme ...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro Extreme Â®','KTEXTCONF0003');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('28809','Apr 11, 2019, 1:39:46 AM','Approved','Saved me','Joe','I had fallen while jogging and landed on my wri...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro Extreme Â®','KTEXTCONF0003');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('28808','Apr 2, 2019, 11:28:05 AM','Approved','Works well for my ankle pain','tiggerteya','I badly sprained my left ankle a year ago and f...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Proâ„¢ USA Black (Packaging May Vary)','10000424');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('28807','Mar 25, 2019, 5:31:47 AM','Approved','The new gentler KT Tape','LMallett','The gentler version curled at the ends in about...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT TapeÂ® Original Cotton Beige','10000024');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('28806','Mar 24, 2019, 12:18:32 AM','Approved','Great product!!','Taylor','I have had shin splints for years because i do ...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT TapeÂ® Original Cotton Black','10000029');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('28804','Mar 7, 2019, 3:31:16 AM','Approved','Amazing!','Jackie','I have an ugly painful keloid scar from surgery...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape ProÂ® Stealth Beige','10000132');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('28802','Feb 22, 2019, 10:15:07 PM','Approved','I am avoiding a knee replacement with Use of KT...','Jan','The tape supports my knee well, and with the st...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape ProÂ® Stealth Beige','10000132');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('28801','Feb 18, 2019, 10:58:10 PM','Approved','Wow this works great!','SToast','Ive started training for my first half maratho...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT TapeÂ® Original Cotton Black','10000029');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('28800','Feb 18, 2019, 6:59:54 PM','Approved','Very good product','GymnastSmith','I use this for my shin splints during track sea...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT TapeÂ® Original Cotton Beige','10000024');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('28799','Feb 18, 2019, 6:48:16 PM','Approved','Do not use for chafing!!','Sarah','I received KT blister prevention tape in my mar...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Performance+Â® Blister Prevention Tape Black','10000679');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('183','Feb 13, 2019, 6:55:03 AM','Approved','Works FANTASTIC FOR ME! GREAT! RELIEF FROM POST OP','I Laugh at the negative comments','I recently began using this product. I unfortun...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape ProÂ® Jet Black','10000138');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('182','Feb 5, 2019, 12:27:00 PM','Approved','Does not stick!','Kristen','Iâ€™ve followed the instructions and itâ€™s falling...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT TapeÂ® Gentle Tape','10001463');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('181','Feb 2, 2019, 12:32:40 PM','Approved','A great product','Les','My feet get very dry in the winter and form cal...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Performance+ Â® Blister Treatment Patch','10000646');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('180','Feb 1, 2019, 9:28:00 PM','Approved','KT Tape: A Gigantic Super Sucker Vacuum Cleaner...','JuneE0871','I LOVE KT Tape!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! I ...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT TAPE Â® COTTON Uncut Pink','10000331');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('179','Jan 26, 2019, 2:55:43 PM','Approved','Not sweat friendly','L_A','Iâ€™m not going to lie - Iâ€™m kind of pissed off t...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT TapeÂ® Original Cotton Beige','10000024');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('178','Jan 22, 2019, 4:14:29 PM','Approved','Shoulder','Katelyn','I hurt my shoulder at a volleyball tournament. ...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Cotton Elastic Sports Tape','KTCTAPCOT0001');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('176','Jan 17, 2019, 3:59:18 PM','Approved','L1 to S1 all damaged','My Broken Back','I recently took a bad fall off my bike and fell...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape ProÂ® Wide','10000644');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('175','Jan 15, 2019, 1:48:09 PM','Approved','Not as good','Kcarr','I bought the cotton version as it said it was s...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT TapeÂ® Original Cotton Beige','10000024');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('174','Jan 12, 2019, 10:22:45 AM','Approved','Great product!','Nicole S','It is amazing. I didnt have any difficulty open...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Recovery+ Â® Ice/Heat Massage Ball','10001723');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('173','Jan 9, 2019, 5:06:27 PM','Approved','Best Roller Ball out there','Gargoyle','I love this roller ball. It has an awesome han...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Recovery+ Â® Ice/Heat Massage Ball','10001723');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('172','Jan 5, 2019, 12:44:11 PM','Approved','Relief for Osteoarthritis in my knee','TallGuy','After months of suffering from the pain of Oste...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape ProÂ® Stealth Beige','10000132');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('171','Jan 4, 2019, 4:17:44 PM','Approved','Skin irritation','Lk','I still had a bad skin reaction after leaving i...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT TapeÂ® Gentle Tape','10001463');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('170','Dec 31, 2018, 8:05:34 PM','Approved','Amazing!','Shuzan','This was my favorite Christmas gift! I donâ€™t kn...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Recovery+ Â® Ice/Heat Massage Ball','10001723');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('169','Dec 29, 2018, 11:45:57 PM','Approved','Surprisingly works!','Ryanne','Iâ€™m a swimmer and due to some unfortunate event...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Recovery+ Recovery Patch Â®','10000381');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('167','Dec 16, 2018, 7:17:40 AM','Approved','Great product','Dave','I started using kt tape about two weeks ago and...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT TapeÂ® Original Cotton Black','10000029');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('166','Dec 16, 2018, 6:02:25 AM','Approved','At first the bar is very hard to open once you ...','GDB','At first the ball is very hard to open, once yo...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Recovery+ Â® Ice/Heat Massage Ball','10001723');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('165','Dec 15, 2018, 7:53:58 PM','Approved','Works Quickly','JD','During a bike race I fell and flaired up my low...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro ExtremeÂ® Jet Black','10001484');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('163','Dec 13, 2018, 4:48:03 AM','Approved','Awesome!!!','jessikillah','Basically, my best friend who was an athletic t...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape ProÂ® Laser Blue','10000144');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('162','Dec 3, 2018, 10:19:42 PM','Approved','Works, with wrinkles','Susan','Using these tapes to prevent blisters while tra...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Performance+Â® Blister Prevention Tape Black','10000679');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('161','Nov 29, 2018, 10:03:55 AM','Approved','Tricky at first','Pluto''s Mom','I got this as a birthday present from my son. W...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Recovery+ Â® Ice/Heat Massage Ball','10001723');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('159','Nov 28, 2018, 9:03:37 PM','Approved','Great product','Jon','Works much better than wearing a bulky knee bra...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Customer','KT Tape ProÂ® Jet Black','10000138');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('158','Nov 23, 2018, 4:13:01 PM','Approved','Works on my Hip Flexors','OldUltraRunner','I was experiencing pain in my Hip Flexors when ...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape ProÂ® Wide','10000644');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('157','Nov 12, 2018, 2:33:10 PM','Approved','This product','noOne','Its great the first time i ever used this produ...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape ProÂ® Sonic Blue','10000159');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('156','Nov 7, 2018, 12:10:25 PM','Approved','KT pro','soreknees','Have bad knees after several decades of working...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro Â®','KTCTAPPRO0001');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('155','Nov 6, 2018, 9:44:51 PM','Approved','Itâ€™s okay','Barefootblonde','I love the KT products but the KT blister tape ...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Performance+Â® Blister Prevention Tape Black','10000679');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('154','Oct 30, 2018, 2:26:23 PM','Approved','Incredible Product','Cajun Thunder','I wasn''t sure if this would work, but am amazed...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape ProÂ® Jet Black','10000138');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('153','Oct 16, 2018, 4:42:23 PM','Approved','Worked like a charm','Liv','Used blister prevention tape to cover a spot wh...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Performance+ Â® Blister Treatment Patch','10000646');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('152','Oct 16, 2018, 9:38:08 AM','Approved','Works great! Less painful!','Nymuse','I love this product! Anything that provides rel...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape ProÂ® Wide','10000644');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('151','Oct 12, 2018, 4:40:10 PM','Approved','Great Product But Wish Adhesion Was A Bit Better','Kate','It really is a essential product for me both fo...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro ExtremeÂ® Jet Black','10001484');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('150','Oct 5, 2018, 8:14:58 PM','Approved','Expensive and doesnâ€™t open easily','Liu','I just bought one and I watched the video onlin...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Recovery+ Â® Ice/Heat Massage Ball','10001723');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('149','Oct 3, 2018, 4:39:41 AM','Approved','Kt recovery','Jackie','Could not open to change from hot to old.','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Recovery+ Â® Ice/Heat Massage Ball','10001723');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('148','Oct 3, 2018, 4:39:40 AM','Approved','Kt recovery','Jackie','Could not open to change from hot to old.','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Recovery+ Â® Ice/Heat Massage Ball','10001723');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('145','Sep 28, 2018, 8:05:24 AM','Approved','Gave it a try...','Kayla','and now fully convinced this is for people who ...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape ProÂ® Jet Black','10000138');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('144','Sep 24, 2018, 9:52:25 PM','Approved','Superior support','Sheri','Applied to reconstructed knee for long tough gr...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape KT Flex Â®','10000383');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('143','Sep 20, 2018, 7:27:17 PM','Approved','Love it!','Geeg','I love this KT tape! The color is super cute! A...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT TapeÂ® Original Cotton Pink','10000046');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('141','Sep 8, 2018, 4:32:57 PM','Approved','Miracle Tape','AM22','I''ve had a shin splints in my right leg for yea...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT TapeÂ® Original Cotton Black','10000029');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('140','Sep 6, 2018, 11:04:20 PM','Approved','Good stuff!','marv','Just applied it to the ball of my foot to help ...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro ExtremeÂ® Jet Black','10001484');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('139','Sep 5, 2018, 6:48:27 AM','Approved','definitely not for extreme','Ben','I just tried using KT Pro Extreme when surfing ...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro ExtremeÂ® Jet Black','10001484');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('138','Sep 4, 2018, 12:43:34 PM','Approved','Can''t go without it...','aussieagilitymom','I''m an active female with scoliosis and daily l...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro ExtremeÂ® Jet Black','10001484');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('137','Aug 29, 2018, 10:22:28 AM','Approved','Magic','Dee','I started having pain in my calves when I was t...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Recovery+ Recovery Patch Â®','10000381');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('136','Aug 27, 2018, 9:46:20 PM','Approved','KT Tape is awesome!','Kyle K.','Did hood to coast last weekend (my first time) ...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT TapeÂ® Original Cotton Beige','10000024');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('135','Aug 27, 2018, 7:36:59 PM','Approved','Best blister prevention we have found!','Dancer','This tape is fantastic! Previously the only thi...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Performance+Â® Blister Prevention Tape Black','10000679');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('133','Aug 9, 2018, 11:52:24 AM','Approved','Not pleased','SW','I recently purchased this tape for shoulder pai...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Customer','KT TapeÂ® Gentle Tape','10001463');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('131','Aug 8, 2018, 11:14:10 AM','Approved','Not Impressed','SW','I just purchased this tape and have not been im...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT TapeÂ® Gentle Tape','10001463');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('130','Aug 6, 2018, 4:45:16 AM','Approved','Better than sleeves.','Haymarie','I have found this product is just right for my...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro-X Â®','10000342');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('129','Aug 1, 2018, 11:00:40 PM','Approved','The best','Hollis','Had arthroscopy chondroplasty done a few weeks ...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape KT Flex Â®','10000383');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('128','Aug 1, 2018, 7:59:05 AM','Approved','Fabulous!!','SsMom','My daughter is a competitive Irish dancer who h...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Performance+Â® Blister Prevention Tape Black','10000679');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('127','Jul 27, 2018, 7:42:49 AM','Approved','A relief for those of us sensitive skin individ...','Pindakaas','I have been using KT Tape for years, but always...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT TapeÂ® Gentle Tape','10001463');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('126','Jul 21, 2018, 6:20:58 PM','Approved','Great for pain relief and support','Miragecats','Love this stuff, I have a few old injuries that...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape ProÂ® Jet Black','10000138');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('125','Jul 21, 2018, 7:20:00 AM','Approved','Worked great on nerve pain neck','Tennis','Working Great','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape ProÂ® Jet Black','10000138');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('124','Jul 20, 2018, 10:31:54 AM','Approved','outstanding!!!','pam','use it all of the time. regular kt tape needs m...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro-X Â®','10000342');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('123','Jul 18, 2018, 2:41:21 PM','Approved','Miraculous','Rhea','This stuff works amazing for knee pain. But do ...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape ProÂ® Solar Yellow','10000161');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('122','Jul 15, 2018, 8:22:41 PM','Approved','KT Blister Treatment Patch','Wendy','I put the patch on both feet after I got a blis...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Customer','KT Performance+ Â® Blister Treatment Patch','10000646');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('121','Jul 12, 2018, 11:23:20 AM','Approved','Test','aloke','The quick brown foxThe quick brown foxThe quick...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT TapeÂ® Original Cotton Beige','10000024');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('120','Jul 12, 2018, 8:53:41 AM','Approved','So-So','LJ','I have gone through 3 boxes of the Gentle tape ...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT TapeÂ® Gentle Tape','10001463');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('119','Jul 11, 2018, 12:50:40 PM','Approved','This product is the truth!','T','I''m 4 weeks out from My knee being scoped. This...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape KT Flex Â®','10000383');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('118','Jul 11, 2018, 3:06:53 AM','Approved','Good Product-comfortable with some support','ClaraT','Bought and tried on wrist and knee. Tape on wri...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Cotton Elastic Sports Tape','KTCTAPCOT0001');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('117','Jul 8, 2018, 6:44:09 PM','Approved','Does not say on while swimming.','Phoebe','I bought it thinking it would stay on better in...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro ExtremeÂ® Jet Black','10001484');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('116','Jul 5, 2018, 1:20:21 PM','Approved','Alright but doesn''t last','KC','I had the KT pro tape previously but it wasn''t ...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT TapeÂ® Original Cotton Blue','10000034');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('115','Jun 27, 2018, 10:52:31 PM','Approved','Not worth the price','Mandy','Bought this tape at a local drug store after u...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape ProÂ® Jet Black','10000138');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('114','Jun 24, 2018, 11:11:54 AM','Approved','Not worth it','Ghawl','I bought this thinking it would be good to use ...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT TapeÂ® Gentle Tape','10001463');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('113','Jun 18, 2018, 5:41:03 AM','Approved','No Water Resistance','Doc Brute','I was hoping this would hold being sweaty and a...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro ExtremeÂ® Jet Black','10001484');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('112','Jun 15, 2018, 12:01:39 PM','Approved','perfect for swim meets and water polo','Mox','I''m on my high school water polo and swim team,...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro ExtremeÂ® Jet Black','10001484');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('111','Jun 13, 2018, 6:38:32 PM','Approved','Not impressed','Cricri','Had to replace tape twice in 1 day after gettin...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT TapeÂ® Original Cotton Beige','10000024');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('110','Jun 9, 2018, 6:35:33 AM','Approved','Bad product','Katie','Not to standard I would expect. It doesn''t stay...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT TapeÂ® Gentle Tape','10001463');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('109','Jun 5, 2018, 3:44:29 PM','Approved','I call it miraculous','Rhea','I have knee pain that doctors can''t figure out ...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Customer','KT Tape ProÂ® Jet Black','10000138');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('108','May 21, 2018, 12:15:59 AM','Approved','Good product','Nicky','I was told that this stuff works good. I bought...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT TapeÂ® Original Cotton Black','10000029');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('107','May 15, 2018, 3:39:24 PM','Approved','L1 Compression Fracture','TSutt','I have pain from an injury suffered in a car ac...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape ProÂ® Wide','10000644');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('106','May 10, 2018, 7:19:26 PM','Approved','WOW','claire','KT tape has helped me so much! I suffer from so...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape ProÂ® Laser Blue','10000144');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('105','May 7, 2018, 8:25:13 PM','Approved','Great product','Sydney','This was my first time using kt tape and I am v...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape ProÂ® Jet Black','10000138');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('104','May 3, 2018, 4:19:03 PM','Approved','Long Lasting','JD','Very refreshing to have constant pain and muscl...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape ProÂ® Stealth Beige','10000132');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('103','May 3, 2018, 10:22:11 AM','Approved','PERFECT','Sky','I''m a lifeguard, and swim instructor. I''ve used...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro ExtremeÂ® Jet Black','10001484');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('102','Apr 29, 2018, 9:12:02 PM','Approved','Amazing!','I_Dont_Know','It is more expensive online than in store and I...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT TapeÂ® Original Cotton Black','10000029');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('101','Apr 21, 2018, 10:12:35 PM','Approved','I bought these on a whim today after a long day...','Sapphire','I''ll buy those as long as my knees hurt & they ...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape KT Flex Â®','10000383');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('100','Apr 20, 2018, 1:52:52 PM','Approved','It works well','stufff glufff','I have been using KT tape and it has been a Sig...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape ProÂ® Jet Black','10000138');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('99','Apr 11, 2018, 7:39:43 AM','Approved','Didn''t stay on','LF','What a disappointment, I''ve been using kttape p...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape KT Flex Â®','10000383');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('98','Apr 1, 2018, 1:32:47 PM','Approved','Extreme','Surf','I like the fact this tape adheres longer. Tapi...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro ExtremeÂ® Jet Black','10001484');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('97','Apr 1, 2018, 11:54:55 AM','Approved','A++++','Tanya','Works good on my knee and upper back Thanks KT','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT TapeÂ® Original Cotton Purple','10000048');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('96','Apr 1, 2018, 11:53:46 AM','Approved','A++','Tee','Works great on my back','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape ProÂ® Wide','10000644');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('95','Mar 29, 2018, 7:19:05 AM','Approved','Love this!','Alex','I use these on my foot - can''t run without them...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro-X Â®','10000342');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('94','Mar 19, 2018, 3:23:13 PM','Approved','not that durable','locci','I really like using of these because it looks c...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape ProÂ® Sonic Blue','10000159');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('93','Mar 19, 2018, 3:16:32 PM','Approved','Injured shoulder, before and after','Jeff','I tore the labrum in my shoulder 20 years ago. ...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Customer','KT Tape Pro ExtremeÂ® Jet Black','10001484');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('92','Feb 23, 2018, 6:27:32 AM','Approved','I like this colour','Lucas','I would like to buy this','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Blue Crystals','10000431');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('91','Feb 18, 2018, 6:11:32 PM','Approved','Great product','Jmc','I have oa in my left knee and I am on my feet a...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Cotton Elastic Sports Tape','KTCTAPCOT0001');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('90','Feb 16, 2018, 4:09:04 PM','Approved','Good but sometimes takes >1 applicatipni','Kam','4/5 see note','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Ultrastick','KTCACCULT0001');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('89','Feb 15, 2018, 9:56:12 PM','Approved','Less than 48 hrs','Tara','Lasted less than 48 hrs before it started peeli...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro Kinesiology Tape','KTCTAPPRO0001-old');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('87','Jan 29, 2018, 7:25:07 PM','Approved','Great for in the water','Eve','Iâ€™m a competitive swimmer and have shoulder iss...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro ExtremeÂ® Jet Black','10001484');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('86','Jan 28, 2018, 8:53:04 AM','Approved','Good Enough For Tommy, Good Enough For Me','TB12 Fan','I have not used this product but did witness To...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro ExtremeÂ® Jet Black','10001484');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('84','Jan 23, 2018, 4:09:54 PM','Approved','Came in super-handy','G.O.A.T.','Covered up some stitches and enabled me to perf...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro Kinesiology Tape','KTCTAPPRO0001-old');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('83','Jan 18, 2018, 9:10:01 AM','Approved','Not as advertised','Mario','I recently purchased a KT Pro Tape with bar cod...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro Kinesiology Tape','KTCTAPPRO0001-old');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('82','Jan 11, 2018, 11:33:41 AM','Approved','Love KT Tape','JennO','I Tape everything, tore my ACL in January and u...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro Kinesiology Tape','KTCTAPPRO0001-old');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('81','Jan 2, 2018, 8:28:50 AM','Approved','lower back and torn shoulder','pestpatrol','first time trying this product on my shoulder a...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape ProÂ® Wide','10000644');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('80','Dec 15, 2017, 6:28:48 PM','Approved','No water resistance','Swimmer','I tried using this tape multiple times when swi...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro ExtremeÂ® Jet Black','10001484');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('79','Dec 14, 2017, 7:28:13 AM','Approved','Think Twice Before Buying','Roger','I have been using KT Tape for years because it ...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT TapeÂ® Gentle Tape','10001463');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('78','Dec 4, 2017, 6:53:43 PM','Approved','Kt tape','Somer','I have bicep tendonitis and was instructed by a...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Cotton Elastic Sports Tape','KTCTAPCOT0001');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('77','Dec 3, 2017, 2:33:28 PM','Approved','Shoulder cuff tear','Shelly','I fell over three years ago and ended up hittin...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Recovery+ Recovery Patch Â®','10000381');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('76','Dec 2, 2017, 12:02:09 PM','Approved','basketball','Jayden','I''ve had pain in my knees from playing basketba...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Customer','KT Tape Cotton Elastic Sports Tape','KTCTAPCOT0001');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('75','Dec 1, 2017, 12:50:12 AM','Approved','Love it.','Mismay','I ruptured my Achilles tendent well playing vol...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro ExtremeÂ® Jet Black','10001484');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('74','Nov 27, 2017, 10:19:53 AM','Approved','Awesome!!','Bowler1019','Used the KT Flex for the first time and it''s aw...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape KT Flex Â®','10000383');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('73','Nov 26, 2017, 11:01:24 PM','Approved','Awesome','Snow','I was very skeptical at first as I have really ...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro Kinesiology Tape','KTCTAPPRO0001-old');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('72','Nov 25, 2017, 1:50:27 PM','Approved','Does not stick','Sue','I''ve been using the cotton KT Tape on my knees ...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT TapeÂ® Gentle Tape','10001463');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('70','Nov 18, 2017, 7:03:35 PM','Approved','Inner/Outer knee pain','Savannah','I''ve played soccer for 4 years now and I use th...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Cotton Elastic Sports Tape','KTCTAPCOT0001');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('69','Nov 17, 2017, 8:26:41 AM','Approved','5','Granger74','60+plus hours for miniscus /mcl, injury 75-95%i...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro Kinesiology Tape','KTCTAPPRO0001-old');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('68','Nov 16, 2017, 9:18:55 AM','Approved','Meant to last','Matt','I play rugby and football and have had several ...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro Kinesiology Tape','KTCTAPPRO0001-old');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('67','Nov 13, 2017, 5:20:53 PM','Approved','Strong','Hilma','I definitely works the support is amazing, howe...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro Kinesiology Tape','KTCTAPPRO0001-old');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('66','Nov 11, 2017, 5:01:16 AM','Approved','Adhesive does not work','Donna','Tape falls off in a few hours. Adhesive does n...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT TapeÂ® Gentle Tape','10001463');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('65','Nov 11, 2017, 4:53:42 AM','Approved','Does not WEAR WELL','Donna','Adhesive does not work well. It starts peeling...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT TapeÂ® Gentle Tape','10001463');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('64','Nov 6, 2017, 12:53:14 PM','Approved','Amazing','Moha','Super helpful, however very expensive.','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Cotton Elastic Sports Tape','KTCTAPCOT0001');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('63','Nov 2, 2017, 8:42:06 AM','Approved','Best ever','Thatsarah101','I am a 45-year-old salsa dancer and part-time p...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro Kinesiology Tape','KTCTAPPRO0001-old');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('62','Oct 26, 2017, 4:54:07 AM','Approved','Donâ€™t last','Tiff','I put this tape on my knee about 12 hours ago a...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT TapeÂ® Original Cotton Blue','10000034');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('61','Oct 26, 2017, 4:42:08 AM','Approved','Fantastic','Crue','I am a personal trainer and my in-home services...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Recovery+ Recovery Patch Â®','10000381');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('60','Oct 17, 2017, 2:38:37 AM','Approved','First time KTTape','Lodope','Itâ€™s great! The area in my lower back stop hurt...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape PRO USA (Packaging May Vary)','KTCTAPUSA0001');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('59','Oct 13, 2017, 7:16:11 AM','Approved','Not sweatproof','John D','Unfortunately for me, I tried to use this tape ...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro ExtremeÂ® Jet Black','10001484');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('58','Oct 12, 2017, 6:17:44 AM','Approved','Amazing','Mia','The tape makes a huge difference for my knee wh...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Cotton Elastic Sports Tape','KTCTAPCOT0001');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('57','Oct 11, 2017, 10:51:52 AM','Approved','Overpriced hype from KT Tape','T West','MUELLER tape does the same thing for $3.99 at W...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro Kinesiology Tape','KTCTAPPRO0001-old');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('56','Oct 10, 2017, 10:04:07 AM','Approved','Holding me together','VinniG','I''m only 56 but like most of my friends, I''ve w...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro ExtremeÂ® Jet Black','10001484');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('54','Oct 9, 2017, 9:02:03 PM','Approved','I have Fibromyalgia','Mypain','And I have tried everything and I refuse to tak...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Recovery+ Recovery Patch Â®','10000381');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('53','Oct 8, 2017, 9:17:24 AM','Approved','For my clients and myself - Never leave home wi...','Micah T. Hartsock','As a Corrective Exercise Professional and Full-...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Uncut Pro','KTCCLIUCP0001');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('52','Oct 5, 2017, 8:30:46 AM','Approved','idk','Micheal Phelps','Tis tape is 1 of the worst ones i''ve used','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro Kinesiology Tape','KTCTAPPRO0001-old');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('51','Oct 3, 2017, 4:35:29 PM','Approved','It works well!','Debbie','I have been using KT tape for about a year. I u...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro Kinesiology Tape','KTCTAPPRO0001-old');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('50','Oct 3, 2017, 1:47:14 PM','Approved','I use KT tape for my unstable ankle and runners...','Bestthingever','It works great! It gave me support and relief w...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro Kinesiology Tape','KTCTAPPRO0001-old');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('49','Oct 1, 2017, 7:34:12 PM','Approved','Good when it wants to be','Kaseyt87','I''m a Y nat swimmer and varsity soccer player a...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro ExtremeÂ® Jet Black','10001484');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('48','Sep 29, 2017, 2:53:34 PM','Approved','Good Quality that stand out','Ayman','This is a good quality product, I have tried se...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro ExtremeÂ® Jet Black','10001484');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('47','Sep 27, 2017, 4:40:34 AM','Approved','I feel hustled. Wish I could select zero stars....','NCKickboxer','I usually use the KT Pro, because the regular c...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro ExtremeÂ® Jet Black','10001484');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('46','Sep 24, 2017, 2:09:01 PM','Approved','Awesome!','Lisa','I fractured my tibial spine and fibula..I also ...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape KT Flex Â®','10000383');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('45','Sep 23, 2017, 9:51:37 PM','Approved','I want my money back','Kate','Not waterproof at all. Definitely no good for r...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro Kinesiology Tape','KTCTAPPRO0001-old');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('44','Sep 16, 2017, 10:56:28 AM','Approved','Disappointed','Hortonok','Used in the past and was happy enough, but eith...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro Kinesiology Tape','KTCTAPPRO0001-old');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('43','Sep 14, 2017, 1:55:56 AM','Approved','Nasty','Pro surfer','Avoid this toxic stuff at all costs. Severe bli...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT TapeÂ® Original Cotton Lime','10000042');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('42','Sep 9, 2017, 2:51:31 PM','Approved','Frustrated','Doug','Had to try your product. But what I got was fro...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro ExtremeÂ® Jet Black','10001484');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('41','Sep 6, 2017, 6:08:58 PM','Approved','Absolutely Fantastic','B.G.','This tape is the best thing for my knee. I got ...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro Kinesiology Tape','KTCTAPPRO0001-old');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('40','Sep 6, 2017, 12:59:15 PM','Approved','Love this tape!','Agility dog','Have severe knee issues and am waiting on a tot...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT TapeÂ® Original Cotton Lime','10000042');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('39','Sep 5, 2017, 4:51:57 AM','Approved','Average','RickS','Went to apply on my wife, who has shoulder pain...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Cotton Elastic Sports Tape','KTCTAPCOT0001');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('38','Sep 3, 2017, 12:54:35 AM','Approved','Loving the KTape','Loving the tape.','I us KTape for Tennis Elbow. I have been using ...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro Kinesiology Tape','KTCTAPPRO0001-old');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('37','Aug 31, 2017, 2:37:38 PM','Approved','Took this to the Track and Field State Meet','Em','I used this all through my indoor and outdoor t...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro ExtremeÂ® Jet Black','10001484');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('36','Aug 30, 2017, 10:00:23 PM','Approved','Does the trick. Awesome product','Alixandrea','Stays on for the state''s amount of days. Holds ...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Customer','KT Tape ProÂ® Laser Blue','10000144');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('35','Aug 30, 2017, 9:55:39 PM','Approved','Comfortable and yet still effective','Alixandrea','LOVE KT Tape! IT''S MY GO-TO for every ache and ...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Customer','KT Tape Cotton Elastic Sports Tape','KTCTAPCOT0001');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('34','Aug 30, 2017, 8:51:06 PM','Approved','Best tape !','Alexus','I''m a amateur boxer so I always get knots on my...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro Kinesiology Tape','KTCTAPPRO0001-old');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('32','Aug 13, 2017, 5:34:46 PM','Approved','Fantastic product','MikeP','Ruptured my right Achilles in Oct. 2016. Did n...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Cotton Elastic Sports Tape','KTCTAPCOT0001');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('31','Aug 12, 2017, 10:00:52 AM','Approved','The best thing ever!!!','Danni','Thus tape is the only thing I''ve found to actua...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro Kinesiology Tape','KTCTAPPRO0001-old');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('30','Aug 5, 2017, 1:41:14 AM','Approved','Stays on all day even while I''m maneuvering','Becca','I''m a vet tech and travel from farm to farm wor...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro ExtremeÂ® Jet Black','10001484');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('29','Aug 2, 2017, 10:06:15 PM','Approved','Love the KT tape Flex not the color','Catcher''s Mom','My daughter''s knee hurts while catching and she...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape KT Flex Â®','10000383');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('27','Jul 27, 2017, 9:36:14 PM','Approved','great','z123','A few years back I tore muscles in my hip while...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro Kinesiology Tape','KTCTAPPRO0001-old');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('24','Jul 20, 2017, 3:45:36 PM','Approved','Trying it and now love it','Mike127th','I am trying on an ankle issue, and the support ...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Cotton Elastic Sports Tape','KTCTAPCOT0001');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('23','Jul 19, 2017, 9:07:31 PM','Approved','Softball','Heidi','i love kt tape it is so helpful, when ur playin...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Cotton Elastic Sports Tape','KTCTAPCOT0001');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('21','Jul 13, 2017, 4:10:00 PM','Approved','Painful','Joseph S.','I bought this because I liked the concept of th...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro-X Â®','10000342');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('20','Jul 12, 2017, 10:27:56 AM','Approved','I tried the stripes and I like them so far.','Lisa','Trying them on my mom''s back today to see if sh...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Cotton Elastic Sports Tape','KTCTAPCOT0001');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('19','Jul 3, 2017, 11:06:30 PM','Approved','Best thing ever invented','Sports','I play rugby and do multiple types of dance. I ...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro Kinesiology Tape','KTCTAPPRO0001-old');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('18','Jul 2, 2017, 12:53:55 PM','Approved','It Works','Dee','I''ve used KT tape for 6 months. Always was sat...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro Kinesiology Tape','KTCTAPPRO0001-old');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('17','Jun 26, 2017, 5:10:42 PM','Approved','So impressed','ElanorLMT','My mom has been having knee pain for the past s...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro Kinesiology Tape','KTCTAPPRO0001-old');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('15','Jun 25, 2017, 9:59:05 PM','Approved','Try it','Jewson','This is by far the best thing to use for reliev...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro Kinesiology Tape','KTCTAPPRO0001-old');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('13','Jun 22, 2017, 4:46:46 AM','Approved','Great product!!','Shelly','Highly recommend for knee icing and heat. Conve...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Recovery+ Â® Ice/Heat Wrap','10000382');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('12','Jun 17, 2017, 11:47:25 AM','Approved','Awesome!','Jane','Had ACL surgery and the therapist put these str...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape KT Flex Â®','10000383');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('11','Jun 16, 2017, 1:52:31 PM','Approved','Absolutely Love These!','Skull_Princess','I received this as a birthday gift last year an...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro-X Â®','10000342');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('9','Jun 9, 2017, 4:58:27 PM','Approved','KT tape','Mole','This is real ,,,I applied it for MCL , INSTANT ...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro Kinesiology Tape','KTCTAPPRO0001-old');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('8','May 31, 2017, 3:05:52 PM','Approved','Immediate Support!','Whitney','I am an equestrian (I ride horses), which has b...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro Kinesiology Tape','KTCTAPPRO0001-old');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('7','May 25, 2017, 6:27:25 PM','Approved','Tried It','TheBeav','Tried this new model for the first time today.....','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT TapeÂ® Gentle Tape','10001463');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('6','May 19, 2017, 9:00:44 AM','Approved','Stays put, keeps me on my feet 12 hours','Mandi, RN','I''m an RN in a busy hospital setting. I'' also ...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT Tape Pro ExtremeÂ® Jet Black','10001484');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('5','May 14, 2017, 10:18:25 PM','Approved','great!','lance','the tape looks nice and works great for strains','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT TapeÂ® Proâ„¢ USA Blue (Packaging May Vary)','10000425');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('3','Apr 6, 2017, 7:27:11 AM','Approved','Awesome Stuff!','Joseppie Gonzales','This tape is just as it states. Gentle and comf...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Guest','KT TapeÂ® Gentle Tape','10001463');
# INSERT INTO temp_reviews_export(id, created, status, title, nickname, review, visibility, type, product, sku) Values ('1','Mar 31, 2017, 3:05:27 PM','Approved','Black Skulls Rock','Joseph','Really cool pattern looks good with our mountai...','KT Tape Consumer KT Tape Consumer KT Tape Consumer','Customer','KT Tape Black Skull','10000379');

select cast(created as datetime) as date from temp_reviews_export

