-- ============= [ store : CSW Store View ] ===================
SELECT * FROM `a53979e5_csw_mig`.`store` WHERE `store_id` = 2;

/*
 M2 URL KEY REPORT
 0  |   130202

 M2 URL KEY REPORT
 0  |   145651
 1  |   145651
 2  |   0

 */
select count(*) from catalog_product_entity_varchar where attribute_id=97 and store_id=0;
select count(*) from catalog_product_entity_varchar where attribute_id=97 and store_id=1;
select count(*) from catalog_product_entity_varchar where attribute_id=97 and store_id=2;

/*
 M2 URL KEY REPORT
 0  |   130202

 M2 URL KEY REPORT
 0  |   145651
 1  |   15001
 2  |   0

 */
select count(*) from catalog_product_entity_varchar where attribute_id=71 and store_id=0;
select count(*) from catalog_product_entity_varchar where attribute_id=71 and store_id=1;
select count(*) from catalog_product_entity_varchar where attribute_id=71 and store_id=2;

select * from catalog_product_entity_varchar where attribute_id=71 and store_id=1 and entity_id =190612;
select * from catalog_product_entity_varchar where attribute_id=97 and store_id=1 and entity_id =190612;

select * from catalog_product_entity_varchar where attribute_id=97 and entity_id in (
    SELECT entity_id FROM `a53979e5_csw_mig`.`catalog_product_entity` WHERE `sku` = '19XE212'
);

-- total available records in url rewrite : 12840
SELECT * FROM `url_rewrite` WHERE `entity_id` =190612  AND `entity_type` = 'product';
SELECT * FROM `url_rewrite` WHERE `entity_id` =190612  AND `entity_type` = 'product';
SELECT * FROM `url_rewrite` WHERE `entity_id` =120870  AND `entity_type` = 'product';


-- ======== | Ensure all url keys with m1
-- ======== | Ensure all url keys has url rewrite

-- SELECT count(*) FROM `url_rewrite`;
select * from rgw_catalog_product_entity_url_key_7_jan;

select -- cpev.entity_id ,
       -- cpev.value,
       -- rcpeuk.value,
       CONCAT('UPDATE catalog_product_entity_varchar SET value=','''',rcpeuk.value,'''',' where entity_id=',cpev.entity_id,' and attribute_id=97 ',' and store_id=0 ') as Query
from
     catalog_product_entity_varchar cpev left join rgw_catalog_product_entity_url_key_7_jan rcpeuk on cpev.entity_id=rcpeuk.entity_id
where cpev.attribute_id=97 and cpev.store_id=0
and rcpeuk.attribute_id=97 and rcpeuk.store_id=0
and cpev.value!=rcpeuk.value;

select * from catalog_product_entity_varchar where entity_id=2691 and attribute_id in (97,71)  and store_id=0;
select * from rgw_catalog_product_entity_url_key_7_jan where entity_id=2691 and attribute_id=97  and store_id=0;


select * from rgw_enterprise_url_rewrite_8_jan where store_id=0 and entity_type=3 and request_path like '%catalog/product/view/id%';
-- count : 145645
select count(*) from rgw_enterprise_url_rewrite_8_jan where store_id=0 and entity_type=3;


-- 2 ways to update : update request_path existing or add new
select cpev.entity_id,cpev.value
     -- ,reur.request_path,reur.value_id ,reur.target_path
from
     catalog_product_entity_varchar cpev
         left join rgw_enterprise_url_rewrite_8_jan reur on cpev.entity_id=SUBSTRING_INDEX(SUBSTRING_INDEX(reur.target_path, '/', 5), '/', -1)
where cpev.attribute_id=97  and cpev.store_id=0
and reur.entity_type=3 and reur.store_id=0
and cpev.value=reur.request_path
and cpev.entity_id=2471;


SELECT ur.entity_id,ur.request_path,ur.target_path,
       SUBSTRING_INDEX(SUBSTRING_INDEX(reur.target_path, '/', 5), '/', -1) as entity_id,
       reur.request_path,
       reur.target_path
FROM `url_rewrite` ur
left join rgw_enterprise_url_rewrite_8_jan reur on ur.entity_id!=SUBSTRING_INDEX(SUBSTRING_INDEX(reur.target_path, '/', 5), '/', -1)
WHERE ur.`entity_type` = 'product' and ur.store_id=1
and reur.entity_type=3 and reur.store_id=0
and ur.entity_id=138769;

select * from rgw_enterprise_url_rewrite_8_jan reur where SUBSTRING_INDEX(SUBSTRING_INDEX(reur.target_path, '/', 5), '/', -1) =2390;
select * from `url_rewrite` ur where ur.entity_id=2390;

-- 'INSERT INTO url_rewrite (entity_type, entity_id, request_path,target_path, redirect_type,store_id,description,is_autogenerated,metadata) VALUES (',
-- '''product''',
--    ,'120870', '".$request_path."','".$target_path."','".$redirect_type."','".$store_id."','".$description."','".$is_autogenerated."','".$metaDataValue."'

-- ======================= add new in m2 url rewrite : 145645
select
count(*)
# CONCAT(
#     'INSERT INTO url_rewrite (entity_type, entity_id, request_path,target_path, redirect_type,store_id,description,is_autogenerated,metadata) VALUES (',
#     '''product''',    ',',    SUBSTRING_INDEX(SUBSTRING_INDEX(target_path, '/', 5), '/', -1),     ',',     '''',    request_path,'''',',','''',target_path,'''',',','''','0',    '''',    ',',    '''',    '0',    '''',    ',',    'null',    ',',    '''',    '1',    '''',    ',',    'null',
#     ');'
#     )
from rgw_enterprise_url_rewrite_8_jan
where entity_type=3 and store_id=0 -- 0 : 145645,1 : 0
-- and entity_id=138769;
and not EXISTS (
              select count(*) from url_rewrite ur where ur.entity_type='product' and ur.store_id=1 -- storeid =1 (12425), 0 (0)10
              and ur.entity_id=SUBSTRING_INDEX(SUBSTRING_INDEX(target_path, '/', 5), '/', -1)
);

-- INSERT INTO url_rewrite (entity_type, entity_id, request_path,target_path, redirect_type,store_id,description,is_autogenerated,metadata) VALUES ('product',2133,'chnat-162-3-1-4-resin-nativity-ornament','catalog/product/view/id/2133','0','0',null,'1',null);

select * from  url_rewrite;


-- and SUBSTRING_INDEX(SUBSTRING_INDEX(target_path, '/', 5), '/', -1)=138769;
--              select * from url_rewrite ur where ur.entity_id=138769;


-- URL KEY K AGAINST KTNI ENTITY ID UPDATE HO CHUIKI HEN
SELECT * FROM rgw_catalog_product_entity_url_key_7_jan;

select count(*) from url_rewrite ur where ur.entity_type='product' and ur.store_id=1; -- storeid =1 (12425), 0 (0)10


-- ==================================================================================================================
# select count(*)
# from rgw_enterprise_url_rewrite
# where entity_type=3 and store_id=0
# -- and entity_id=138769;
# and EXISTS (
#               select 1 from url_rewrite ur where ur.entity_type='product' and ur.store_id=0
#               and ur.entity_id=SUBSTRING_INDEX(SUBSTRING_INDEX(target_path, '/', 5), '/', -1)
# );

-- TSG-CH-1852


SELECT e.entity_id AS 'id',
       v1.value AS 'name',
       e.sku,
       d1.value AS 'price',
       cids.category_ids AS 'category_ids',
       cids.category_names AS 'category_names',
       mg.value
FROM  catalog_product_entity e
LEFT JOIN  catalog_product_entity_varchar v1 ON e.entity_id = v1.entity_id
AND v1.store_id = 0
AND v1.attribute_id =169
AND v1.attribute_id =
  (SELECT attribute_id
   FROM  eav_attribute
   WHERE attribute_code = 'name'
     AND entity_type_id =
       (SELECT entity_type_id
        FROM  eav_entity_type
        WHERE entity_type_code = 'catalog_product'))
LEFT JOIN  catalog_product_entity_text t1 ON e.entity_id = t1.entity_id
AND t1.store_id = 0
AND t1.attribute_id =
  (SELECT attribute_id
   FROM  eav_attribute
   WHERE attribute_code = 'short_description'
     AND entity_type_id =
       (SELECT entity_type_id
        FROM  eav_entity_type
        WHERE entity_type_code = 'catalog_product'))
LEFT JOIN  catalog_product_entity_text t2 ON e.entity_id = t2.entity_id
AND t2.store_id = 0
AND t2.attribute_id =
  (SELECT attribute_id
   FROM  eav_attribute
   WHERE attribute_code = 'description'
     AND entity_type_id =
       (SELECT entity_type_id
        FROM  eav_entity_type
        WHERE entity_type_code = 'catalog_product'))
LEFT JOIN  catalog_product_entity_varchar v2 ON e.entity_id = v2.entity_id
AND v2.store_id = 0
AND v2.attribute_id =
  (SELECT attribute_id
   FROM  eav_attribute
   WHERE attribute_code = 'image'
     AND entity_type_id =
       (SELECT entity_type_id
        FROM  eav_entity_type
        WHERE entity_type_code = 'catalog_product'))
LEFT JOIN  catalog_product_entity_varchar v3 ON e.entity_id = v3.entity_id
AND v3.store_id = 0
AND v3.attribute_id =
  (SELECT attribute_id
   FROM  eav_attribute
   WHERE attribute_code = 'thumbnail'
     AND entity_type_id =
       (SELECT entity_type_id
        FROM  eav_entity_type
        WHERE entity_type_code = 'catalog_product'))
LEFT JOIN  catalog_product_entity_decimal d1 ON e.entity_id = d1.entity_id
AND d1.store_id = 0
AND d1.attribute_id =
  (SELECT attribute_id
   FROM  eav_attribute
   WHERE attribute_code = 'price'
     AND entity_type_id =
       (SELECT entity_type_id
        FROM  eav_entity_type
        WHERE entity_type_code = 'catalog_product'))
LEFT JOIN
  (SELECT m1.entity_id,
          GROUP_CONCAT(m2.value) AS value
   FROM  catalog_product_entity_media_gallery_value_to_entity m1
   INNER JOIN  catalog_product_entity_media_gallery m2 ON m2.value_id = m1.value_id
   AND m2.attribute_id =
     (SELECT attribute_id
      FROM  eav_attribute
      WHERE attribute_code = 'media_gallery'
        AND entity_type_id =
          (SELECT entity_type_id
           FROM  eav_entity_type
           WHERE entity_type_code = 'catalog_product'))
   GROUP BY m1.entity_id) mg ON e.entity_id = mg.entity_id
LEFT JOIN
      (SELECT product_id,
              GROUP_CONCAT(c.category_id SEPARATOR ',') AS category_ids,
              GROUP_CONCAT(cv.value SEPARATOR ',')      AS category_names
       FROM catalog_category_product c
                INNER JOIN catalog_category_entity_varchar cv ON c.category_id = cv.entity_id
           AND cv.store_id = 0
           AND cv.attribute_id =
               (SELECT attribute_id
                FROM eav_attribute
                WHERE attribute_code = 'name'
                  AND entity_type_id =
                      (SELECT entity_type_id
                       FROM eav_entity_type
                       WHERE entity_type_code = 'catalog_category'))
   GROUP BY product_id
          ) cids ON e.entity_id = cids.product_id
where -- mg.value is null
      e.sku='BKM-1578'
      cids.category_ids =2224;



select -- cpev.entity_id ,
       -- cpev.value,
       -- rcpeuk.value,
       CONCAT('UPDATE catalog_product_entity_varchar SET value=','''',rcpeuk.value,'''',' where entity_id=',cpev.entity_id,' and attribute_id=97 ',' and store_id=0 ') as Query
from
     catalog_product_entity_varchar cpev left join rgw_catalog_product_entity_url_key_7_jan rcpeuk on cpev.entity_id=rcpeuk.entity_id
where cpev.attribute_id=97 and cpev.store_id=0
and rcpeuk.attribute_id=97 and rcpeuk.store_id=0
and cpev.value!=rcpeuk.value;

-- ================= PRADEEP SCRIPT SQL RESOLTUION ============

SELECT * FROM `url_rewrite` ur WHERE ur.`entity_type` = 'product' and ur.entity_id not in (SELECT rcpeuk.entity_id FROM rgw_catalog_product_entity_url_key_7_jan rcpeuk)

-- 145645-141730 = 3915
-- in products ki csv bana k import it
-- SET FOREIGN_KEY_CHECKS=0;
-- SET FOREIGN_KEY_CHECKS=1;

SELECT CONCAT('INSERT INTO url_rewrite (entity_type, entity_id, request_path,target_path, redirect_type,store_id,description,is_autogenerated,metadata) ' ||
              'VALUES (','''product''',    ',',    entity_id,     ',',     '''',    value,'''',',','''','catalog/product/view/id/',entity_id,'''',',','''','0',    '''',    ',',    '''',    '1',    '''',    ',',    'null',    ',',    '''',    '1',    '''',    ',',    'null',');') as url_rewrite_sql_updates
FROM rgw_catalog_product_entity_url_key_7_jan where entity_id in (select ur.entity_id from url_rewrite ur);
-- INSERT INTO url_rewrite (entity_type, entity_id, request_path,target_path, redirect_type,store_id,description,is_autogenerated,metadata) VALUES ('product',45832,'7130-pope-john-paul-ii-banner-slb7130','catalog/product/view/id/45832','0','1',null,'1',null);

-- ==============================================================================
-- ready inner query
-- 145651 (97+0)
select count(*) from catalog_product_entity_varchar cpev where cpev.attribute_id=97 and cpev.store_id=0;
select entity_id,value from catalog_product_entity_varchar cpev where cpev.attribute_id=97 and cpev.store_id=0 and entity_id=45832;
select * from url_rewrite where entity_id=45832;


select cpev.entity_id,value, cpe.sku,ur.request_path from  catalog_product_entity_varchar cpev
LEFT JOIN catalog_product_entity cpe on cpev.entity_id = cpe.entity_id
LEFT JOIN url_rewrite ur ON cpev.entity_id = ur.entity_id
where cpev.attribute_id=97 and cpev.store_id=1
and cpev.entity_id =2133;

select ur.entity_id,ur.request_path, REPLACE(ur.request_path, "./", "/") from url_rewrite ur where ur.request_path like '%./%' and entity_id=84355;
-- update url_rewrite set request_path=REPLACE(request_path, "./", "/") where request_path like '%./%'


select count(*) from url_rewrite where request_path not like '%.html' and entity_type='product'
and concat(request_path,'.html') not in (        select request_path from url_rewrite where entity_type='product');

-- and entity_id=8127;;


SET @a=(select request_path from url_rewrite where entity_type='product');

CREATE TEMPORARY TABLE IF NOT EXISTS a AS (select request_path from url_rewrite where entity_type='product');
select * from a;


update url_rewrite set request_path=concat(request_path,'.html') where request_path not like '%.html' and entity_type='product'
 and concat(request_path,'.html') not in (    select * from a  );
-- and entity_id=8127;


-- =============== new URL rewrite work ===============

-- __________ CATEGORY WORK STARTS _______________
SELECT * FROM `url_rewrite` where entity_type='product';
SELECT * FROM `url_rewrite` where entity_type='category';
    -- 1. backup current category data and delete it : 361
    CREATE TABLE temp_jan_16_url_rewrite_for_category SELECT * FROM `url_rewrite` where entity_type='category';
    select * from temp_jan_16_url_rewrite_for_category; -- 361
    delete from  `url_rewrite` where entity_type='category';
    -- 2. Import data from m1
    -- verifying existing records in URL rewrite. jo already pare hen unka set exlude krna hoga : 0
    SELECT * FROM `url_rewrite` ur WHERE ur.`entity_type` = 'category' and ur.entity_id not in (SELECT rcpeuk.entity_id FROM rgw_catalog_product_entity_url_key_7_jan rcpeuk)
    SELECT
           CONCAT('INSERT INTO url_rewrite (entity_type, entity_id, request_path,target_path, redirect_type,store_id,description,is_autogenerated,metadata) VALUES (','''category''',    ',',    entity_id,     ',',     '''',    value,'''',',','''','catalog/category/view/id/',entity_id,'''',',','''','0',    '''',    ',',    '''',    '1',    '''',    ',',    'null',    ',',    '''',    '1',    '''',    ',',    'null',');') as url_rewrite_sql_updates
    FROM rgw_catalog_product_entity_url_key_7_jan where entity_id in (select ur.entity_id from url_rewrite ur);
    -- INSERT INTO url_rewrite (entity_type, entity_id, request_path,target_path, redirect_type,store_id,description,is_autogenerated,metadata) VALUES ('product',45832,'7130-pope-john-paul-ii-banner-slb7130','catalog/product/view/id/45832','0','1',null,'1',null);

    SELECT CONCAT('INSERT INTO url_rewrite (entity_type, entity_id, request_path,target_path, redirect_type,store_id,description,is_autogenerated,metadata) VALUES (','''category''',    ',',    reur.new_entity_id,     ',',     '''',    reur.request_path,'''',',','''','catalog/category/view/id/',reur.new_entity_id,'''',',','''','0',    '''',    ',',    '''',    '1',    '''',    ',',    'null',    ',',    '''',    '1',    '''',    ',',    'null',');') as url_rewrite_sql_updates
    from rgw_enterprise_url_rewrite_8_jan  reur where reur.target_path like '%/category%' -- 11188


select * from catalog_category_entity_varchar where attribute_id=97 and entity_id=2185;

-- __________ CATEGORY WORK ENDS _______________
-- url_rewrite_id : 452815
-- entity_id : 2185

-- entity_id product : 191636

select * from catalog_url_rewrite_product_category where category_id=2185
select * from catalog_url_rewrite_product_category where category_id=191636
select * from catalog_category_entity_varchar where entity_id=2185 and store_id=2
SELECT * FROM `url_rewrite` where entity_type='category';

-- catalog/category/view/id/182
-- catalog/category/view/id/2185
select * from url_rewrite  where target_path like '%2185%'
select * from url_rewrite  where target_path like '%catalog/category/view/id/182'
select * from catalog_url_rewrite_product_category where category_id=182 and url_rewrite_id=452132

select * from url_rewrite where entity_type='category'  order by url_rewrite_id desc


SET FOREIGN_KEY_CHECKS=1;
truncate table url_rewrite;
truncate table catalog_url_rewrite_product_category;

select * from catalog_url_rewrite_product_category


-- -------------
-- m2 previous catalog_category_entity: 1408
-- m1 : 1409
select count(*) from catalog_category_entity where entity_id=2926;

select * from catalog_category_entity;
call tbl_count('catalog_category_entity');
-- 8045
select * from customer_entity -- 8043
where email="idchachar@gmail.com"
8045
select * from customer_entity where entity_id=8394
select count(*) from customer_entity -- 8043
select max(entity_id) from customer_entity

-- COUNT AFER IMPORT
select count(*) from customer_entity; -- 8045-> 8560
select count(*) from catalog_product_entity; -- 145651-> 145900
select count(*) from sales_order;    -- 20378-> 22268
select * from sales_order;    -- 20378
select count(*) from sales_order_address; -- 40756->44532

-- '191721-1509-0
select * from catalog_product_entity_int where entity_id=191721 and attribute_id=1509 and store_id=0 order by value_id desc;

select * from catalog_product_entity_int where entity_id=191721 and attribute_id=1509 and store_id=0 order by value_id desc;

select *
from a53979e5_csm1.rgw_catalog_product_entity_int rcpei
inner join a53979e5_csw_mig.catalog_product_entity_int cpe
on rcpei.value_id=cpe.value_id

select * from sequence_rma_item



select count(*) from catalog_product_entity


-- =============== [ ] ===============
SELECT * FROM store;
SELECT * FROM store_website;


update	catalog_product_entity_tier_price	 set website_id=2 where website_id=1;
-- update	catalog_product_index_price	 set website_id=2 where website_id=1;
update	catalog_product_index_price_bundle_opt_tmp	 set website_id=2 where website_id=1;
update	catalog_product_index_price_bundle_sel_tmp	 set website_id=2 where website_id=1;
update	catalog_product_index_price_bundle_tmp	 set website_id=2 where website_id=1;
-- update	catalog_product_index_price_replica	 set website_id=2 where website_id=1;
-- update	catalog_product_index_website	 set website_id=2 where website_id=1;
-- update	catalog_product_website	 set website_id=2 where website_id=1;
update	cataloginventory_stock	 set website_id=2 where website_id=1;
update	cataloginventory_stock_item	 set website_id=2 where website_id=1;
update	cataloginventory_stock_status	 set website_id=2 where website_id=1;
update	cataloginventory_stock_status_replica	 set website_id=2 where website_id=1;
update	catalogrule_product	 set website_id=2 where website_id=1;
update	catalogrule_website	 set website_id=2 where website_id=1;
update	customer_eav_attribute_website	 set website_id=2 where website_id=1;
update	customer_entity	 set website_id=2 where website_id=1;
update	customer_grid_flat	 set website_id=2 where website_id=1;
-- update	inventory_stock_1	 set website_id=2 where website_id=1;
-- update	salesrule_product_attribute	 set website_id=2 where website_id=1;

-- update	salesrule_website	 set website_id=2 where website_id=1;

update	store	 set website_id=2 where website_id=1;

update	store_group	 set website_id=2 where website_id=1;

-- update	store_website	 set website_id=2 where website_id=1;


/*
sql> update	catalog_product_entity_tier_price	 set website_id=2 where website_id=1
[2020-01-29 03:55:34] completed in 239 ms
sql> update	catalog_product_index_price	 set website_id=2 where website_id=1
[2020-01-29 03:55:37] [23000][1062] (conn=91211921) Duplicate entry '2390-0-2' for key 'PRIMARY'
sql> update	catalog_product_index_price	 set website_id=2 where website_id=1
[2020-01-29 03:56:12] [23000][1062] (conn=91211921) Duplicate entry '2390-0-2' for key 'PRIMARY'
sql> update	catalog_product_index_price_bundle_opt_tmp	 set website_id=2 where website_id=1
[2020-01-29 03:56:30] completed in 235 ms
sql> update	catalog_product_index_price_bundle_sel_tmp	 set website_id=2 where website_id=1
[2020-01-29 03:56:34] completed in 241 ms
sql> update	catalog_product_index_price_bundle_tmp	 set website_id=2 where website_id=1
[2020-01-29 03:56:38] completed in 238 ms
sql> update	catalog_product_index_price_replica	 set website_id=2 where website_id=1
[2020-01-29 03:56:43] [23000][1062] (conn=91211921) Duplicate entry '2390-0-2' for key 'PRIMARY'
sql> update	catalog_product_index_website	 set website_id=2 where website_id=1
[2020-01-29 03:57:08] [23000][1062] (conn=91211921) Duplicate entry '2' for key 'PRIMARY'
sql> update	catalog_product_website	 set website_id=2 where website_id=1
[2020-01-29 03:57:21] [23000][1062] (conn=91211921) Duplicate entry '2390-2' for key 'PRIMARY'
sql> update	cataloginventory_stock	 set website_id=2 where website_id=1
[2020-01-29 03:57:32] completed in 236 ms
sql> update	cataloginventory_stock_item	 set website_id=2 where website_id=1
[2020-01-29 03:57:37] completed in 239 ms
sql> update	cataloginventory_stock_status	 set website_id=2 where website_id=1
[2020-01-29 03:57:41] completed in 234 ms
sql> update	cataloginventory_stock_status_replica	 set website_id=2 where website_id=1
[2020-01-29 03:57:44] completed in 241 ms
sql> update	catalogrule_product	 set website_id=2 where website_id=1
[2020-01-29 03:57:49] 308 rows affected in 258 ms
sql> update	catalogrule_website	 set website_id=2 where website_id=1
[2020-01-29 03:57:53] 2 rows affected in 237 ms
sql> update	customer_entity	 set website_id=2 where website_id=1
[2020-01-29 03:57:57] 965 rows affected in 349 ms
sql> update	customer_grid_flat	 set website_id=2 where website_id=1
[2020-01-29 03:58:01] 965 rows affected in 274 ms
sql> update	inventory_stock_1	 set website_id=2 where website_id=1
[2020-01-29 03:58:05] [HY000][1288] (conn=91211921) The target table inventory_stock_1 of the UPDATE is not updatable
sql> update	salesrule_product_attribute	 set website_id=2 where website_id=1
[2020-01-29 03:58:21] [23000][1062] (conn=91211921) Duplicate entry '14-2-0-74' for key 'PRIMARY'
sql> update	salesrule_website	 set website_id=2 where website_id=1
[2020-01-29 03:58:28] [23000][1062] (conn=91211921) Duplicate entry '1-2' for key 'PRIMARY'
sql> update	store	 set website_id=2 where website_id=1
[2020-01-29 03:58:35] 2 rows affected in 301 ms
sql> update	store_group	 set website_id=2 where website_id=1
[2020-01-29 03:58:40] 2 rows affected in 234 ms
sql> update	store_website	 set website_id=2 where website_id=1
[2020-01-29 03:58:44] [23000][1451] (conn=91211921) Cannot delete or update a parent row: a foreign key constraint fails (`a53979e5_csw_mig`.`catalog_product_website`, CONSTRAINT `CATALOG_PRODUCT_WEBSITE_WEBSITE_ID_STORE_WEBSITE_WEBSITE_ID` FOREIGN KEY (`website_id`) REFERENCES `store_website` (`website_id`) ON D)
*/

-- [2020-01-29 03:55:37] [23000][1062] (conn=91211921) Duplicate entry '2390-0-2' for key 'PRIMARY'
-- update	IGNORE catalog_product_index_price	 set website_id=2
 select count (* ) from catalog_product_index_price -- 748670 (252240 has issue and 496430 changed)
where website_id=1;

-- [2020-01-29 03:56:43] [23000][1062] (conn=91211921) Duplicate entry '2390-0-2' for key 'PRIMARY'
-- update ignore catalog_product_index_price_replica	 set website_id=2
select count (* ) from catalog_product_index_price_replica -- 748670 (252240 has issue in changing and 496430 changed)
where website_id=1;

-- [2020-01-29 03:57:08] [23000][1062] (conn=91211921) Duplicate entry '2' for key 'PRIMARY'
-- update	catalog_product_index_website	 set website_id=2
-- select  count(*) from catalog_product_index_website  -- 1
-- where website_id=1;

-- [2020-01-29 03:57:21] [23000][1062] (conn=91211921) Duplicate entry '2390-2' for key 'PRIMARY'
-- update ignore catalog_product_website	 set website_id=2
select  count(*) from catalog_product_website -- 77349 ( 27398 has issue in changing and 49951 changed)
where website_id=1;

-- [2020-01-29 03:58:05] [HY000][1288] (conn=91211921) The target table inventory_stock_1 of the UPDATE is not updatable
-- update ignore	inventory_stock_1	 set website_id=2
select  count(*) from inventory_stock_1  -- 0
where website_id=1;

-- [2020-01-29 03:58:28] [23000][1062] (conn=91211921) Duplicate entry '1-2' for key 'PRIMARY'
-- update ignore	salesrule_website	 set website_id=2
select  count(*) from salesrule_website -- 98 (41 has issue in chaing and 57 changed)
select  * from salesrule_website -- 98 (41 has issue in chaing and 57 changed)
where website_id=1;

--  update	salesrule_website	 set website_id=2 where website_id=1;


-- [2020-01-29 03:58:44] [23000][1451] (conn=91211921) Cannot delete or update a parent row: a foreign key constraint fails (`a53979e5_csw_mig`.`catalog_product_website`, CONSTRAINT `CATALOG_PRODUCT_WEBSITE_WEBSITE_ID_STORE_WEBSITE_WEBSITE_ID` FOREIGN KEY (`website_id`) REFERENCES `store_website` (`website_id`) ON D)
-- update	store_website	 set website_id=2
-- select  count(*) from store_website
-- where website_id=1;
select * from store_website;
select * from store;

-- custom attributes work ---
SELECT * FROM eav_entity_type;

SELECT * FROM `eav_attribute` where entity_type_id=3 and frontend_label in ('Show In Layered Navigation Filter','Display Left Category As','Display Only Left Categories','Home Page Slider Image','Image Text')
union
SELECT * FROM `rgw_eav_attribute` where entity_type_id=3 and frontend_label in ('Show In Layered Navigation Filter','Display Left Category As','Display Only Left Categories','Home Page Slider Image','Image Text');

-- backup for (  Remove CSW Category attributes  )
# INSERT INTO a53979e5_csw_mig.eav_attribute (attribute_id, entity_type_id, attribute_code, attribute_model, backend_model, backend_type, backend_table, frontend_model, frontend_input, frontend_label, frontend_class, source_model, is_required, is_user_defined, default_value, is_unique, note) VALUES (1420, 3, 'display_left_category', null, null, 'int', null, null, 'select', 'Display Left Category As', null, 'Plumtree\\Categoryattribute\\Model\\Category\\Attribute\\Source\\DisplayLeftCategory', 0, 0, null, 0, null);
# INSERT INTO a53979e5_csw_mig.eav_attribute (attribute_id, entity_type_id, attribute_code, attribute_model, backend_model, backend_type, backend_table, frontend_model, frontend_input, frontend_label, frontend_class, source_model, is_required, is_user_defined, default_value, is_unique, note) VALUES (1419, 3, 'display_left_nav', null, null, 'int', null, null, 'boolean', 'Display Only Left Categories', null, null, 0, 0, null, 0, null);
# INSERT INTO a53979e5_csw_mig.eav_attribute (attribute_id, entity_type_id, attribute_code, attribute_model, backend_model, backend_type, backend_table, frontend_model, frontend_input, frontend_label, frontend_class, source_model, is_required, is_user_defined, default_value, is_unique, note) VALUES (1408, 3, 'm_show_in_layered_navigation', null, null, 'int', null, null, 'select', 'Show In Layered Navigation Filter', null, 'Magento\\Eav\\Model\\Entity\\Attribute\\Source\\Boolean', 0, 1, '1', 0, null);
# INSERT INTO a53979e5_csw_mig.eav_attribute (attribute_id, entity_type_id, attribute_code, attribute_model, backend_model, backend_type, backend_table, frontend_model, frontend_input, frontend_label, frontend_class, source_model, is_required, is_user_defined, default_value, is_unique, note) VALUES (2915, 3, 'show_in_layered_navigation', null, null, 'int', null, null, 'boolean', 'Show In Layered Navigation Filter', null, null, 0, 0, null, 0, null);
# INSERT INTO a53979e5_csw_mig.eav_attribute (attribute_id, entity_type_id, attribute_code, attribute_model, backend_model, backend_type, backend_table, frontend_model, frontend_input, frontend_label, frontend_class, source_model, is_required, is_user_defined, default_value, is_unique, note) VALUES (1423, 3, 'slider_image', null, 'Magento\\Catalog\\Model\\Category\\Attribute\\Backend\\Image', 'varchar', null, null, 'image', 'Home Page Slider Image', null, null, 0, 0, null, 0, null);
-- re insterd
-- INSERT INTO a53979e5_csw_mig.eav_attribute (attribute_id, entity_type_id, attribute_code, attribute_model, backend_model, backend_type, backend_table, frontend_model, frontend_input, frontend_label, frontend_class, source_model, is_required, is_user_defined, default_value, is_unique, note) VALUES (1424, 3, 'image_text', null, null, 'text', null, null, 'textarea', 'Image Text', null, null, 0, 0, null, 0, null);

select 'catalog_product_bundle_price_index' as table_name, count(*) as tbl_count from catalog_product_bundle_price_index;
select 'catalog_product_bundle_price_index' as table_name, count(*) as tbl_count from catalog_product_bundle_price_index UNION ALL
select 'catalog_product_bundle_selection_price' as table_name, count(*) as tbl_count from catalog_product_bundle_selection_price UNION ALL
select 'catalog_product_bundle_stock_index' as table_name, count(*) as tbl_count from catalog_product_bundle_stock_index UNION ALL
select 'catalog_product_entity_tier_price' as table_name, count(*) as tbl_count from catalog_product_entity_tier_price UNION ALL
select 'catalog_product_index_price' as table_name, count(*) as tbl_count from catalog_product_index_price UNION ALL
select 'catalog_product_index_price_bundle_idx' as table_name, count(*) as tbl_count from catalog_product_index_price_bundle_idx UNION ALL
select 'catalog_product_index_price_bundle_opt_idx' as table_name, count(*) as tbl_count from catalog_product_index_price_bundle_opt_idx UNION ALL
select 'catalog_product_index_price_bundle_opt_tmp' as table_name, count(*) as tbl_count from catalog_product_index_price_bundle_opt_tmp UNION ALL
select 'catalog_product_index_price_bundle_sel_idx' as table_name, count(*) as tbl_count from catalog_product_index_price_bundle_sel_idx UNION ALL
select 'catalog_product_index_price_bundle_sel_tmp' as table_name, count(*) as tbl_count from catalog_product_index_price_bundle_sel_tmp UNION ALL
select 'catalog_product_index_price_bundle_tmp' as table_name, count(*) as tbl_count from catalog_product_index_price_bundle_tmp UNION ALL
select 'catalog_product_index_price_cfg_opt_agr_idx' as table_name, count(*) as tbl_count from catalog_product_index_price_cfg_opt_agr_idx UNION ALL
select 'catalog_product_index_price_cfg_opt_agr_tmp' as table_name, count(*) as tbl_count from catalog_product_index_price_cfg_opt_agr_tmp UNION ALL
select 'catalog_product_index_price_cfg_opt_idx' as table_name, count(*) as tbl_count from catalog_product_index_price_cfg_opt_idx UNION ALL
select 'catalog_product_index_price_cfg_opt_tmp' as table_name, count(*) as tbl_count from catalog_product_index_price_cfg_opt_tmp UNION ALL
select 'catalog_product_index_price_downlod_idx' as table_name, count(*) as tbl_count from catalog_product_index_price_downlod_idx UNION ALL
select 'catalog_product_index_price_downlod_tmp' as table_name, count(*) as tbl_count from catalog_product_index_price_downlod_tmp UNION ALL
select 'catalog_product_index_price_final_idx' as table_name, count(*) as tbl_count from catalog_product_index_price_final_idx UNION ALL
select 'catalog_product_index_price_final_tmp' as table_name, count(*) as tbl_count from catalog_product_index_price_final_tmp UNION ALL
select 'catalog_product_index_price_idx' as table_name, count(*) as tbl_count from catalog_product_index_price_idx UNION ALL
select 'catalog_product_index_price_opt_agr_idx' as table_name, count(*) as tbl_count from catalog_product_index_price_opt_agr_idx UNION ALL
select 'catalog_product_index_price_opt_agr_tmp' as table_name, count(*) as tbl_count from catalog_product_index_price_opt_agr_tmp UNION ALL
select 'catalog_product_index_price_opt_idx' as table_name, count(*) as tbl_count from catalog_product_index_price_opt_idx UNION ALL
select 'catalog_product_index_price_opt_tmp' as table_name, count(*) as tbl_count from catalog_product_index_price_opt_tmp UNION ALL
select 'catalog_product_index_price_replica' as table_name, count(*) as tbl_count from catalog_product_index_price_replica UNION ALL
select 'catalog_product_index_price_tmp' as table_name, count(*) as tbl_count from catalog_product_index_price_tmp UNION ALL
select 'catalog_product_index_tier_price' as table_name, count(*) as tbl_count from catalog_product_index_tier_price UNION ALL
select 'catalog_product_index_website' as table_name, count(*) as tbl_count from catalog_product_index_website UNION ALL
select 'catalog_product_website' as table_name, count(*) as tbl_count from catalog_product_website UNION ALL
select 'cataloginventory_stock' as table_name, count(*) as tbl_count from cataloginventory_stock UNION ALL
select 'cataloginventory_stock_item' as table_name, count(*) as tbl_count from cataloginventory_stock_item UNION ALL
select 'cataloginventory_stock_status' as table_name, count(*) as tbl_count from cataloginventory_stock_status UNION ALL
select 'cataloginventory_stock_status_idx' as table_name, count(*) as tbl_count from cataloginventory_stock_status_idx UNION ALL
select 'cataloginventory_stock_status_replica' as table_name, count(*) as tbl_count from cataloginventory_stock_status_replica UNION ALL
select 'cataloginventory_stock_status_tmp' as table_name, count(*) as tbl_count from cataloginventory_stock_status_tmp UNION ALL
select 'catalogrule_group_website' as table_name, count(*) as tbl_count from catalogrule_group_website UNION ALL
select 'catalogrule_group_website_replica' as table_name, count(*) as tbl_count from catalogrule_group_website_replica UNION ALL
select 'catalogrule_product' as table_name, count(*) as tbl_count from catalogrule_product UNION ALL
select 'catalogrule_product_price' as table_name, count(*) as tbl_count from catalogrule_product_price UNION ALL
select 'catalogrule_product_price_replica' as table_name, count(*) as tbl_count from catalogrule_product_price_replica UNION ALL
select 'catalogrule_product_replica' as table_name, count(*) as tbl_count from catalogrule_product_replica UNION ALL
select 'catalogrule_website' as table_name, count(*) as tbl_count from catalogrule_website UNION ALL
select 'customer_eav_attribute_website' as table_name, count(*) as tbl_count from customer_eav_attribute_website UNION ALL
select 'customer_entity' as table_name, count(*) as tbl_count from customer_entity UNION ALL
select 'customer_grid_flat' as table_name, count(*) as tbl_count from customer_grid_flat UNION ALL
select 'downloadable_link_price' as table_name, count(*) as tbl_count from downloadable_link_price UNION ALL
select 'email_automation' as table_name, count(*) as tbl_count from email_automation UNION ALL
select 'email_contact' as table_name, count(*) as tbl_count from email_contact UNION ALL
select 'email_importer' as table_name, count(*) as tbl_count from email_importer UNION ALL
-- select 'inventory_stock_1' as table_name, count(*) as tbl_count from inventory_stock_1 UNION ALL
select 'paypal_cert' as table_name, count(*) as tbl_count from paypal_cert UNION ALL
select 'persistent_session' as table_name, count(*) as tbl_count from persistent_session UNION ALL
select 'product_alert_price' as table_name, count(*) as tbl_count from product_alert_price UNION ALL
select 'product_alert_stock' as table_name, count(*) as tbl_count from product_alert_stock UNION ALL
select 'salesrule_product_attribute' as table_name, count(*) as tbl_count from salesrule_product_attribute UNION ALL
select 'salesrule_website' as table_name, count(*) as tbl_count from salesrule_website UNION ALL
select 'search_synonyms' as table_name, count(*) as tbl_count from search_synonyms UNION ALL
select 'sendfriend_log' as table_name, count(*) as tbl_count from sendfriend_log UNION ALL
select 'shipping_tablerate' as table_name, count(*) as tbl_count from shipping_tablerate UNION ALL
select 'store' as table_name, count(*) as tbl_count from store UNION ALL
select 'store_group' as table_name, count(*) as tbl_count from store_group UNION ALL
select 'store_website' as table_name, count(*) as tbl_count from store_website UNION ALL
select 'vertex_custom_option_flex_field' as table_name, count(*) as tbl_count from vertex_custom_option_flex_field UNION ALL
select 'weee_tax' as table_name, count(*) as tbl_count from weee_tax;





select 'catalog_product_entity_tier_price' as table_name, count(*) as tbl_count from catalog_product_entity_tier_price where website_id=2 UNION ALL
select 'catalog_product_index_price' as table_name, count(*) as tbl_count from catalog_product_index_price where website_id=2 UNION ALL
select 'catalog_product_index_price_bundle_opt_tmp' as table_name, count(*) as tbl_count from catalog_product_index_price_bundle_opt_tmp where website_id=2 UNION ALL
select 'catalog_product_index_price_bundle_sel_tmp' as table_name, count(*) as tbl_count from catalog_product_index_price_bundle_sel_tmp where website_id=2 UNION ALL
select 'catalog_product_index_price_bundle_tmp' as table_name, count(*) as tbl_count from catalog_product_index_price_bundle_tmp where website_id=2 UNION ALL
select 'catalog_product_index_price_replica' as table_name, count(*) as tbl_count from catalog_product_index_price_replica where website_id=2 UNION ALL
select 'catalog_product_index_website' as table_name, count(*) as tbl_count from catalog_product_index_website where website_id=2 UNION ALL
select 'catalog_product_website' as table_name, count(*) as tbl_count from catalog_product_website where website_id=2 UNION ALL
select 'cataloginventory_stock' as table_name, count(*) as tbl_count from cataloginventory_stock where website_id=2 UNION ALL
select 'cataloginventory_stock_item' as table_name, count(*) as tbl_count from cataloginventory_stock_item where website_id=2 UNION ALL
select 'cataloginventory_stock_status' as table_name, count(*) as tbl_count from cataloginventory_stock_status where website_id=2 UNION ALL
select 'cataloginventory_stock_status_replica' as table_name, count(*) as tbl_count from cataloginventory_stock_status_replica where website_id=2 UNION ALL
select 'cataloginventory_stock_status_tmp' as table_name, count(*) as tbl_count from cataloginventory_stock_status_tmp where website_id=2 UNION ALL
select 'catalogrule_product' as table_name, count(*) as tbl_count from catalogrule_product where website_id=2 UNION ALL
select 'catalogrule_website' as table_name, count(*) as tbl_count from catalogrule_website where website_id=2 UNION ALL
select 'customer_eav_attribute_website' as table_name, count(*) as tbl_count from customer_eav_attribute_website where website_id=2 UNION ALL
select 'customer_entity' as table_name, count(*) as tbl_count from customer_entity where website_id=2 UNION ALL
select 'customer_grid_flat' as table_name, count(*) as tbl_count from customer_grid_flat where website_id=2
UNION ALL
-- select 'inventory_stock_1' as table_name, count(*) as tbl_count from inventory_stock_1 where website_id=2 UNION ALL
select 'salesrule_product_attribute' as table_name, count(*) as tbl_count from salesrule_product_attribute where website_id=2 UNION ALL
select 'salesrule_website' as table_name, count(*) as tbl_count from salesrule_website where website_id=2 UNION ALL
select 'store' as table_name, count(*) as tbl_count from store where website_id=2 UNION ALL
select 'store_group' as table_name, count(*) as tbl_count from store_group where website_id=2 UNION ALL
select 'store_website' as table_name, count(*) as tbl_count from store_website where website_id=2;


/*
update ignore	catalog_product_index_price	 set website_id=1 where website_id=2;
update ignore	catalog_product_index_price_bundle_opt_tmp	 set website_id=1 where website_id=2;
update ignore	catalog_product_index_price_bundle_sel_tmp	 set website_id=1 where website_id=2;
update ignore	catalog_product_index_price_bundle_tmp	 set website_id=1 where website_id=2;
update ignore	catalog_product_index_price_replica	 set website_id=1 where website_id=2;
update ignore	catalog_product_index_website	 set website_id=1 where website_id=2;
update ignore	catalog_product_website	 set website_id=1 where website_id=2;
update ignore	catalogrule_product	 set website_id=1 where website_id=2;
update ignore	catalogrule_website	 set website_id=1 where website_id=2;
update ignore	customer_entity	 set website_id=1 where website_id=2;
update ignore	customer_grid_flat	 set website_id=1 where website_id=2;
update ignore	salesrule_product_attribute	 set website_id=1 where website_id=2;
update ignore	salesrule_website	 set website_id=1 where website_id=2;
-- update ignore	store	 set website_id=1 where website_id=2;
update ignore	store_group	 set website_id=1 where website_id=2;
*/
select * from catalog_product_index_price where website_id=2;

select 'catalog_product_index_price' as table_name, count(*) as tbl_count from catalog_product_index_price where website_id=2 UNION ALL
select 'catalog_product_index_price_bundle_opt_tmp' as table_name, count(*) as tbl_count from catalog_product_index_price_bundle_opt_tmp where website_id=2 UNION ALL
select 'catalog_product_index_price_bundle_sel_tmp' as table_name, count(*) as tbl_count from catalog_product_index_price_bundle_sel_tmp where website_id=2 UNION ALL
select 'catalog_product_index_price_bundle_tmp' as table_name, count(*) as tbl_count from catalog_product_index_price_bundle_tmp where website_id=2 UNION ALL
select 'catalog_product_index_price_replica' as table_name, count(*) as tbl_count from catalog_product_index_price_replica where website_id=2 UNION ALL
select 'catalog_product_index_website' as table_name, count(*) as tbl_count from catalog_product_index_website where website_id=2 UNION ALL
select 'catalog_product_website' as table_name, count(*) as tbl_count from catalog_product_website where website_id=2 UNION ALL
select 'catalogrule_product' as table_name, count(*) as tbl_count from catalogrule_product where website_id=2 UNION ALL
select 'catalogrule_website' as table_name, count(*) as tbl_count from catalogrule_website where website_id=2 UNION ALL
select 'customer_entity' as table_name, count(*) as tbl_count from customer_entity where website_id=2 UNION ALL
select 'customer_grid_flat' as table_name, count(*) as tbl_count from customer_grid_flat where website_id=2 UNION ALL
select 'salesrule_product_attribute' as table_name, count(*) as tbl_count from salesrule_product_attribute where website_id=2 UNION ALL
select 'salesrule_website' as table_name, count(*) as tbl_count from salesrule_website where website_id=2 UNION ALL
select 'store' as table_name, count(*) as tbl_count from store where website_id=2 UNION ALL
select 'store_group' as table_name, count(*) as tbl_count from store_group where website_id=2 UNION ALL
select 'store_website' as table_name, count(*) as tbl_count from store_website where website_id=2 ; --  UNION ALL


-- ===================== [ shipper carrier wala kaaaaam ] ===============
-- remove these elements after taking backup ================== DONE : DADA
select * from core_config_data;
-- select * from core_config_data where value like '%shipper%';
 select * from core_config_data where value like '%carrier_shipper%';
-- delete from core_config_data where value like '%carrier_shipper%'
select * from core_config_data where value like '%carrier_shipper%';
select * from core_config_data where updated_at like '2020-02-18%';

select * from rgw_catalog_product_entity_varchar
-- select * from product_att
where attribute_id in (
    select distinct attribute_id from eav_attribute where attribute_code like '%shipper%'
    );
     select * from eav_attribute where attribute_code like '%shipper%';
-- 1149-advent-candle-refill-tiny-tapers
select * from rgw_catalog_product_entity_url_key

-- select rcpev.value,ea.attribute_code
select *
from rgw_catalog_product_entity_varchar rcpev
-- inner join eav_attribute ea on rcpev.attribute_id=ea.attribute_id
-- where entity_id=2610
where rcpev.attribute_id=1470
group by rcpev.value,ea.attribute_code;

select * from eav_attribute where attribute_code='attr_shipping_width';
select * from eav_attribute where frontend_label like '%Shipping%';
select * from rgw_eav_attribute where attribute_code like '%shipper%';

select * from catalog_product_link_attribute_varchar;
SELECT * FROM rgw_eav_attribute WHERE `source_model` like '%shipperhq%';

-- kum jo
select * from catalog_product_entity_varchar where attribute_id in (1456,1457,1458,1459,1460,1461,1462,1463,1464,1465,1466,1467,1468,1469,1471,1473,1475)

select distinct  attribute_id from rgw_catalog_product_entity_varchar  where attribute_id in (1456,1457,1458,1459,1460,1461,1462,1463,1464,1465,1466,1467,1468,1469,1471,1473,1475)
select * from rgw_catalog_product_entity_varchar  where attribute_id in (1456,1457,1458,1459,1460,1461,1462,1463,1464,1465,1466,1467,1468,1469,1471,1473,1475)

-- backup table
# create table temp_march_13_catalog_product_entity_varchar
# select * from catalog_product_entity_varchar;
-- insert into table
-- count before insert: 3709000
-- count after insert: xxxxx
select count(*) from catalog_product_entity_varchar;
select value_id, attribute_id, store_id, entity_id, value from rgw_catalog_product_entity_varchar  where attribute_id in (1456,1457,1458,1459,1460,1461,1462,1463,1464,1465,1466,1467,1468,1469,1471,1473,1475);

insert ignore into catalog_product_entity_varchar(value_id, attribute_id, store_id, entity_id, value)
select value_id,
       (case
           when attribute_id = 1456 then 2895
           when attribute_id = 1465 then 2903
           when attribute_id = 1466 then 2907
           end ) as attribute_id,
       store_id, entity_id, value
from rgw_catalog_product_entity_varchar  where attribute_id in (1456,1465,1466);
select * from catalog_product_entity where entity_id=186802
select * from catalog_product_entity_varchar where entity_id=186802


select * from eav_attribute where attribute_id in (2895,2903,2907);

select value_id,
      attribute_id,
       store_id, entity_id, value
from catalog_product_entity_varchar  where attribute_id in (2895,2903,2907);


select * from quote_shipping_rate


select * from catalog_product_entity_varchar where value_id not in (
    select value_id from temp_march_13_catalog_product_entity_varchar
    )
select * from rgw_eav_attribute where attribute_id in (1456,1465,1466);
# 1456    shipperhq_shipping_group    2895
# 1465    shipperhq_dim_group         2903
# 1466    shipperhq_poss_boxes        2907
select * from eav_attribute where attribute_code in ('shipperhq_shipping_group','shipperhq_dim_group','shipperhq_poss_boxes');

-- hi m1 m check krne paregne
select * from eav_entity_varchar  where attribute_id in (1456,1457,1458,1459,1460,1461,1462,1463,1464,1465,1466,1467,1468,1469,1471,1473,1475)
select * from eav_entity_attribute  where attribute_id in (1456,1457,1458,1459,1460,1461,1462,1463,1464,1465,1466,1467,1468,1469,1471,1473,1475)
select * from eav_entity_varchar  where attribute_id in (1456,1457,1458,1459,1460,1461,1462,1463,1464,1465,1466,1467,1468,1469,1471,1473,1475)


(select attribute_id from rgw_eav_attribute where attribute_code like '%shipperhq%');

-- [2020-02-29 04:18:24] [1364] Field 'carrier_code' doesn't have a default value
select * from shipperhq_order_packages;
INSERT ignore into shipperhq_order_packages(package_id, order_id, carrier_group_id, package_name, length, width, height, weight, declared_value, surcharge_price)
select package_id, order_id, carrier_group_id, package_name, length, width, height, weight, declared_value, surcharge_price from rgw_shipperhq_order_packages;

select * from shipperhq_order_package_items;
INSERT ignore into shipperhq_order_package_items(package_id, sku, qty_packed, weight_packed)
select package_id, sku, qty_packed, weight_packed from rgw_shipperhq_order_package_items;

select * from shipperhq_quote_packages;
INSERT ignore into shipperhq_quote_packages(carrier_group_id, carrier_code, package_name, length, width, height, weight, declared_value, surcharge_price)
select carrier_group_id, carrier_code, package_name, length, width, height, weight, declared_value, surcharge_price from rgw_shipperhq_quote_packages;

set foreign_key_checks =1;

select * from shipperhq_quote_package_items;
INSERT ignore into shipperhq_quote_package_items(package_id, sku, qty_packed, weight_packed)
select package_id, sku, qty_packed, weight_packed from rgw_shipperhq_quote_package_items;

select * from shipperhq_synchronize;
INSERT ignore into shipperhq_synchronize(attribute_code, attribute_type, value, status, date_added)
select attribute_code, attribute_type, value, status, date_added from rgw_shipperhq_synchronize;

select 'shipperhq_order_packages' as table_name, count(*) as count from shipperhq_order_packages union
select 'shipperhq_order_package_items' as table_name, count(*) as count from shipperhq_order_package_items  union
select 'shipperhq_quote_packages' as table_name, count(*) as count from shipperhq_quote_packages union
select 'shipperhq_quote_package_items' as table_name, count(*) as count from shipperhq_quote_package_items  union
select 'shipperhq_synchronize' as table_name, count(*) as count from shipperhq_synchronize;



# select * from shipperhq_storage;
# INSERT ignore into
# select * from rgw_shipperhq_storage;
#
# select * from shipperhq_suburb_lookup;
# INSERT ignore into
# select * from rgw_shipperhq_suburb_lookup;


select count(*) from shipperhq_order_detail;
select count(*) from shipperhq_quote_item_detail;
select count(*) from shipperhq_quote_address_item_detail;
select count(*) from shipperhq_order_item_detail;
select count(*) from shipperhq_quote_packages;
select count(*) from shipperhq_quote_package_items;
select count(*) from shipperhq_order_packages;
select count(*) from shipperhq_order_package_items;
select count(*) from shipperhq_order_detail_grid;

-- Back up
/*
INSERT INTO a53979e5_csw_mig.core_config_data (config_id, scope, scope_id, path, value, updated_at) VALUES (2807, 'default', 0, 'carriers/shqflat/model', 'shipperhq_shipper/carrier_shipper', '2020-01-06 14:08:00');
INSERT INTO a53979e5_csw_mig.core_config_data (config_id, scope, scope_id, path, value, updated_at) VALUES (2808, 'default', 0, 'carriers/shqusps/model', 'shipperhq_shipper/carrier_shipper', '2020-01-06 14:08:00');
INSERT INTO a53979e5_csw_mig.core_config_data (config_id, scope, scope_id, path, value, updated_at) VALUES (2809, 'default', 0, 'carriers/shqfree/model', 'shipperhq_shipper/carrier_shipper', '2020-01-06 14:08:00');
INSERT INTO a53979e5_csw_mig.core_config_data (config_id, scope, scope_id, path, value, updated_at) VALUES (2810, 'default', 0, 'carriers/shqups/model', 'shipperhq_shipper/carrier_shipper', '2020-01-06 14:08:00');
INSERT INTO a53979e5_csw_mig.core_config_data (config_id, scope, scope_id, path, value, updated_at) VALUES (2811, 'default', 0, 'carriers/multicarrier/model', 'shipperhq_shipper/carrier_shipper', '2020-01-06 14:08:00');
INSERT INTO a53979e5_csw_mig.core_config_data (config_id, scope, scope_id, path, value, updated_at) VALUES (2812, 'default', 0, 'carriers/shqflat1/model', 'shipperhq_shipper/carrier_shipper', '2020-01-06 14:08:00');
INSERT INTO a53979e5_csw_mig.core_config_data (config_id, scope, scope_id, path, value, updated_at) VALUES (2813, 'default', 0, 'carriers/shqdhl/model', 'shipperhq_shipper/carrier_shipper', '2020-01-06 14:08:00');
INSERT INTO a53979e5_csw_mig.core_config_data (config_id, scope, scope_id, path, value, updated_at) VALUES (2814, 'default', 0, 'carriers/shqflat2/model', 'shipperhq_shipper/carrier_shipper', '2020-01-06 14:08:00');
*/
-- reverting my attributes after pravin installation of extension
# INSERT INTO a53979e5_csw_mig.core_config_data (config_id, scope, scope_id, path, value, updated_at) VALUES (2812, 'default', 0, 'carriers/shqflat1/model', 'shipperhq_shipper/carrier_shipper', '2020-01-06 14:08:00');
# INSERT INTO a53979e5_csw_mig.core_config_data (config_id, scope, scope_id, path, value, updated_at) VALUES (2814, 'default', 0, 'carriers/shqflat2/model', 'shipperhq_shipper/carrier_shipper', '2020-01-06 14:08:00');
# INSERT INTO a53979e5_csw_mig.core_config_data (config_id, scope, scope_id, path, value, updated_at) VALUES (3400, 'default', 0, 'carriers/shqusps/model', 'ShipperHQ\\Shipper\\Model\\Carrier\\Shipper', '2020-02-26 06:20:29');
# INSERT INTO a53979e5_csw_mig.core_config_data (config_id, scope, scope_id, path, value, updated_at) VALUES (3401, 'default', 0, 'carriers/shqdhl/model', 'ShipperHQ\\Shipper\\Model\\Carrier\\Shipper', '2020-02-26 06:20:29');
# INSERT INTO a53979e5_csw_mig.core_config_data (config_id, scope, scope_id, path, value, updated_at) VALUES (3402, 'default', 0, 'carriers/shqups/model', 'ShipperHQ\\Shipper\\Model\\Carrier\\Shipper', '2020-02-26 06:20:29');
# INSERT INTO a53979e5_csw_mig.core_config_data (config_id, scope, scope_id, path, value, updated_at) VALUES (3403, 'default', 0, 'carriers/shqflat/model', 'ShipperHQ\\Shipper\\Model\\Carrier\\Shipper', '2020-02-26 06:20:29');
# INSERT INTO a53979e5_csw_mig.core_config_data (config_id, scope, scope_id, path, value, updated_at) VALUES (3405, 'default', 0, 'carriers/shqfree/model', 'ShipperHQ\\Shipper\\Model\\Carrier\\Shipper', '2020-02-26 06:22:51');

-- ====================================================================
select * from customer_entity where email='info@stgregory.net';
select * from customer_entity where email='info@stgregory.net';
select * from customer_entity where website_id is null;

select * from customer_entity where website_id=0;

select * from catalog_product_index_website where website_id=0;
select * from catalog_product_entity_text where store_id is null;
select * from catalog_product_entity_tier_price where website_id=0;
select * from catalog_product_index_price where website_id=0;
select * from catalog_product_index_price_bundle_opt_tmp where website_id=0;
select * from catalog_product_index_price_bundle_sel_tmp where website_id=0;
select * from catalog_product_index_price_bundle_tmp where website_id=0;
select * from catalog_product_index_price_replica where website_id=0;
select * from catalog_product_index_website where website_id=0;
select * from catalog_product_website where website_id=0;


-- https://www.churchsupplywarehouse.com/apparel-vestments./religious-ties.html

select * from url_rewrite where request_path like '%religious-ties.html%'





select * from eav_attribute;


6
select count(*) from catalog_category_entity; -- 1410
select count(*) from sales_order; -- 22268
select count(*) from customer_address_entity -- 7139
select count(*) from url_rewrite; -- 283487
select count(*) from url_rewrite where entity_type='product'; -- 281376
select count(*) from url_rewrite where entity_type='category'; -- 2111
select * from customer_address_entity where entity_id='1062'-- 7139

SELECT
     e.sku, COUNT(m.value) as cnt
FROM catalog_product_entity e
LEFT JOIN catalog_product_entity_media_gallery_value_to_entity r
    ON e.entity_id = r.entity_id
LEFT JOIN catalog_product_entity_media_gallery m
    ON r.value_id = m.value_id
# where e.sku='NOVO70'
# where e.sku='SLB50-511'
GROUP BY
    e.entity_id
HAVING
    cnt = 0


-- ===================== [ starts RGW images missing ] ==============
-- 3rd m2 (attrID:88) vs m1 (attrID:xx) : attrCode : media_gallery
-- -------------------------------
# /r/6/r6000ams-8121.jpg
SELECT * FROM `catalog_product_entity_media_gallery` where value like '/r/6/r6000ams-8121.jpg'
# 2 found where value_id : 615052,643189
SELECT * FROM `catalog_product_entity_media_gallery_value_to_entity` where value_id  in (615052,643189)
# 2 found where value_id		entity
# 		615052		96464
# 		643189		108848
-- -------------------------------

# /r/6/hir3552-652.jpg
SELECT * FROM `catalog_product_entity_media_gallery` where value like '/r/6/hir3552-652.jpg'
SELECT * FROM `catalog_product_entity_media_gallery` where value not like '%/r/6/%'
SELECT * FROM `catalog_product_entity_media_gallery` where value like '%hir3552-652.jpg%'
SELECT * FROM `catalog_product_entity_media_gallery` where value like '%bkm-1578.jpg%'

SELECT * FROM `catalog_product_entity_media_gallery` where value like '%bkm-1578.jpg%'
-- bkm-1578.jpg
SELECT * FROM `catalog_product_entity_media_gallery` where value like '%mjmwhite_5_22_2015_4_38_53_pm%';
SELECT * FROM `rgw_catalog_product_entity_media_gallery` where value like '%21903%';
SELECT * FROM `rgw_catalog_product_entity_media_gallery` where value like '%bkm-1578.jpg%';
SELECT * FROM `catalog_product_entity_media_gallery_value_to_entity` where value_id =632506

SELECT * FROM `catalog_product_entity_media_gallery` where value not like '%/r/6/%';

# 2 found where value_id : 615052,643189
SELECT * FROM `catalog_product_entity_media_gallery_value_to_entity` where value_id  in (615052,643189)

-- ab esi products ki list nikalne hen jo root pe hen
SELECT * FROM `catalog_product_entity_media_gallery` where value like '%mjmwhite_5_22_2015_4_38_53_pm%';

SELECT distinct
                CONCAT('/',SUBSTRING(value, 2, 1),'/',SUBSTRING(value, 3, 1),value) AS new_path,
    value,
    ROUND (
        (
            LENGTH(value)
            - LENGTH( REPLACE ( value, '/', '') )
        ) / LENGTH('/')
    ) AS count
FROM catalog_product_entity_media_gallery where ROUND (
        (
            LENGTH(value)
            - LENGTH( REPLACE ( value, '/', '') )
        ) / LENGTH('/')
    )=1
and value like  '%68308.jpg%'
create table temp_apr_4_catalog_product_entity_media_gallery
select * from
(SELECT distinct
                CONCAT('/',SUBSTRING(value, 2, 1),'/',SUBSTRING(value, 3, 1),value) AS new_path,
    value,
    ROUND (
        (
            LENGTH(value)
            - LENGTH( REPLACE ( value, '/', '') )
        ) / LENGTH('/')
    ) AS count
FROM catalog_product_entity_media_gallery where ROUND (
        (
            LENGTH(value)
            - LENGTH( REPLACE ( value, '/', '') )
        ) / LENGTH('/')
    )=1) A
select * from temp_apr_4_catalog_product_entity_media_gallery limit  1
create table temp_apr_4_catalog_product_entity_media_gallery_actual_bkp
select * from catalog_product_entity_media_gallery

select * from catalog_product_entity_media_gallery where value_id =2544
select * from temp_apr_4_catalog_product_entity_media_gallery_actual_bkp


create table temp_apr_4_catalog_product_entity_media_gallery_actual_bkp2
select * from temp_apr_4_catalog_product_entity_media_gallery_actual_bkp
truncate table temp_apr_4_catalog_product_entity_media_gallery_actual_bkp2
select * from temp_apr_4_catalog_product_entity_media_gallery_actual_bkp2

insert into temp_apr_4_catalog_product_entity_media_gallery_actual_bkp2
select * from temp_apr_4_catalog_product_entity_media_gallery_actual_bkp

SET FOREIGN_KEY_CHECKS=0;
truncate table catalog_product_entity_media_gallery
select * from catalog_product_entity_media_gallery

insert into catalog_product_entity_media_gallery
select * from temp_apr_4_catalog_product_entity_media_gallery_actual_bkp
SET FOREIGN_KEY_CHECKS=1;
select count(*) from catalog_product_entity_media_gallery
select * from temp_apr_4_catalog_product_entity_media_gallery

-- TODO images path update : DONE
--  update catalog_product_entity_media_gallery set value=(CONCAT('/',SUBSTRING(value, 2, 1),'/',SUBSTRING(value, 3, 1),value)) where value in (select distinct value from temp_apr_4_catalog_product_entity_media_gallery);

select * from  temp_apr_4_catalog_product_entity_media_gallery;

select * from  catalog_product_entity_media_gallery
where value like '%19659%';
select * from  catalog_product_entity_media_gallery_value_to_entity
where entity_id=191214

select * from catalog_product_entity where sku like '%19659%'
# update catalog_product_entity_media_gallery set value=(select a.new_path from temp_apr_4_catalog_product_entity_media_gallery a where a.value=value limit  1)
#  where value in (select distinct value from temp_apr_4_catalog_product_entity_media_gallery);


SELECT CONCAT('/',SUBSTRING('/9352GF.jpg', 2, 1),'/',SUBSTRING('/9352GF.jpg', 3, 1),'/9352GF.jpg');

select * from catalog_product_entity_media_gallery where value like  '%68308.jpg%'


# 2 found where value_id		entity
# 		615052		96464
# 		643189		108848
-- -------------------------------

-- ===================== [ ends RGW images missing ] ==============

-- ====================== [ shipperhq_warehouse shipperhq work started ] ===============
select * from rgw_eav_attribute where attribute_code like '%ship%' union all
select * from eav_attribute where attribute_code like '%ship%'

select * from catalog_product_entity cpe
left join url_rewrite ur on cpe.entity_id=ur.entity_id and ur.entity_type='product'
where ur.entity_id is null

select * from catalog_product_entity cpe where cpe.entity_id not in
(select entity_id from url_rewrite where entity_type='product')

select * from catalog_product_entity cpe
where cpe.entity_id not in
(select count(entity_id) from url_rewrite where entity_type='product' and store_id=3)

select count(entity_id) from url_rewrite where entity_type='product' and store_id=2;
select * from catalog_product
select * from store


select * from catalog_product_entity_varchar where attribute_id=43;


select * from eav_attribute where entity_type_id=3

SELECT * FROM 'catalog_product_entity_varchar' WHERE 'attribute_id' = 121

SELECT * FROM `hqatts` where attribute_code='shipperhq_warehouse'


-- alter table hqatts change value m1_value text charset utf8 null comment 'Value';
-- alter table hqatts	add m2_value text null;

select reaov.option_id,p.m1_value    ,'=vs=', p.attribute_code, eaov.value
from  rgw_eav_attribute_option_value reaov
inner join `hqatts` p on reaov.option_id=p.m1_value and p.m1_value is not null
inner join eav_attribute_option_value eaov on p.attribute_code=eaov.value;



select p.attribute_code, eaov.value from  `hqatts` p
inner join eav_attribute_option_value eaov on p.attribute_code=eaov.value;

SELECT * FROM `a53979e5_csw_mig`.`rgw_eav_attribute` WHERE `attribute_id` = 752


SELECT * FROM `rgw_eav_attribute_option` WHERE `option_id` = 7667

-- drop table hqatts_unique
-- CREATE TABLE hqatts_unique select * from  (SELECT distinct  attribute_id, attribute_code, m1_value,m2_value FROM hqatts p where p.attribute_code='shipperhq_warehouse' and m1_value is not null) a

select * from hqatts

select * from rgw_eav_attribute_option where attribute_id=1457

select * from rgw_eav_attribute_option where attribute_id=1457
select * from hqatts_unique

-- 7667
SELECT * FROM eav_attribute_option WHERE `option_id` = 7667;
SELECT * FROM rgw_eav_attribute_option_value where option_id=6404;


select * from rgw_eav_attribute_option_value  where value='ECUMENICUS' and option_id in (select distinct  option_id from rgw_eav_attribute_option where attribute_id=1457);
select * from eav_attribute_option_value eaov where value='ECUMENICUS' and option_id in (select distinct  option_id from eav_attribute_option where attribute_id=2896);

CREATE TABLE temp_mar_30_eav_attribute_option_value
select a.option_id as m1_option_id,b.option_id as m2_option_id , a.value,a.store_id
from
( select * from rgw_eav_attribute_option_value  where option_id in (select distinct  option_id from rgw_eav_attribute_option where attribute_id=1457) order by value) a
inner join
(select * from eav_attribute_option_value eaov where option_id in (select distinct  option_id from eav_attribute_option where attribute_id=2896) order by value) b
on a.value=b.value;
-- where a.option_id=6404 -- test


select * from temp_mar_30_eav_attribute_option_value

select * from rgw_catalog_product_entity_text  where entity_id=192017

select * from hqatts  where entity_id=192017 and  attribute_id=1457;
select * from catalog_product_entity_text  where entity_id=192017 and  attribute_id=2896;

select attribute_id, store_id, entity_id, value
from catalog_product_entity_text  where entity_id=192017 and  attribute_id=2896;

-- create catalog_product_entity_text like rows
select attribute_id,0 as store_id,entity_id, m2_value value from hqatts  where entity_id=192017 and  attribute_id=1457;

-- 144704
CREATE TABLE temp_mar_30_catalog_product_entity_text
SELECT * FROM
(select p.attribute_id,0 as store_id,p.entity_id, cast(eaov.m2_option_id as CHAR(50)) as value
from hqatts p
inner join temp_mar_30_eav_attribute_option_value eaov on p.m1_value=eaov.m1_option_id) A
where -- eaov.m2_option_id=7667 and
      p.entity_id=192017

select * from temp_mar_30_catalog_product_entity_text
where entity_id not in (select entity_id from catalog_product_entity_text a where a.attribute_id=2896 and a.store_id=0)
and entity_id=192017;

select count(entity_id) from catalog_product_entity_text a
where a.attribute_id=2896 and a.store_id=0
-- and entity_id=192017
  and value is not null


select * from catalog_product_entity_text a
where a.attribute_id=2896 and a.store_id=0
-- and entity_id=192017
  and value is not null



# SELECT attribute_id, attribute_code FROM `eav_attribute` WHERE attribute_code like '%hq%'
# SELECT  attribute_id, attribute_code  FROM `rgw_eav_attribute` WHERE attribute_code like '%hq%'

# create table temp_mar_31_catalog_product_entity_text_bkp select * from catalog_product_entity_text
# select count(*) from temp_mar_31_catalog_product_entity_text_bkp
# select count(*) from catalog_product_entity_text

-- Chunk 1
--  UPDATE catalog_product_entity_text a INNER JOIN temp_mar_30_catalog_product_entity_text b ON a.entity_id = b.entity_id and a.attribute_id=2896 SET a.value = b.value



select * from temp_mar_30_catalog_product_entity_text
where entity_id in (select entity_id from catalog_product_entity_text a where a.attribute_id=2896 and a.store_id=0  and a.value is null)

select * from catalog_product_entity_text a where a.attribute_id=2896 and a.store_id=0 and a.value is null


-- for verification
select p.attribute_id,0 as store_id,p.entity_id, cast(eaov.m2_option_id as CHAR(50)) as value, eaov.m1_option_id
from hqatts p
inner join temp_mar_30_eav_attribute_option_value eaov on p.m1_value=eaov.m1_option_id
-- drop table temp_mar_31_catalog_product_entity_text_bkp
-- ====================== [ shipperhq_warehouse shipperhq work ended ] ===============


# select * from rgw_catalog_product_entity_media_gallery;
# select * from rgw_catalog_product_entity_media_gallery_value;
# SELECT * FROM `rgw_catalog_product_entity_media_gallery` where value like '%hir3552-652.jpg%'
# SELECT * FROM `catalog_product_entity_media_gallery` where value like '%hir3552-652.jpg%'


select * from eav_attribute_set
select * from eav_attribut
select * from eav_attribute
where attribute_set_name like '%ship%'

select * from eav_attribute_set
where attribute_set_name like '%ship%'


-- Sacraments (ID: 13)
SELECT * FROM `catalog_category_entity_text`
where entity_id=13  and attribute_id in (1420,1419,1424,1408,2915,1423);

SELECT * FROM eav_entity_type;

SELECT * FROM `eav_attribute` where entity_type_id=3 and frontend_label in ('Show In Layered Navigation Filter','Display Left Category As','Display Only Left Categories','Home Page Slider Image','Image Text')
union
SELECT * FROM `rgw_eav_attribute` where entity_type_id=3 and frontend_label in ('Show In Layered Navigation Filter','Display Left Category As','Display Only Left Categories','Home Page Slider Image','Image Text');
-- 1420
-- 1419,3,display_left_nav -- value =1
SELECT * FROM `catalog_category_entity_text` where entity_id=13
SELECT * FROM `rgw_catalog_category_entity_text` where entity_id=13

SELECT * FROM `catalog_category_entity_int` where entity_id=13 and attribute_id=1420 union
SELECT * FROM `catalog_category_entity_text` where entity_id=13 and attribute_id=1420 union
SELECT * FROM `catalog_category_entity_varchar` where entity_id=13 and attribute_id=1420 union
SELECT * FROM `catalog_category_entity_decimal` where entity_id=13 and attribute_id=1420 union
SELECT * FROM `catalog_category_entity_datetime` where entity_id=13 and attribute_id=1420;


select * from eav_attribute where attribute_id=57
select * from eav_attribute where attribute_id=45
select * from eav_attribute where attribute_id=47
select * from eav_attribute where attribute_id=58
select * from eav_attribute where attribute_id=62
select * from eav_attribute where attribute_id=186
select * from eav_attribute where attribute_id=1492

SELECT * FROM `catalog_category_entity_varchar` where entity_id=13

select * from eav_attribute_option where attribute_id=1419
select * from rgw_eav_attribute_option
where attribute_id=1419

select * from eav_attribute_option_value

select * from hqatts where attribute_id=1419

select * from eav_entity_text

where attribute_id=1419


SELECT `cpev_s`.*,
       `cpev_0`.`value` AS `store_value`
FROM   `catalog_product_entity_varchar` `cpev_s`
       JOIN `eav_attribute` `ea`
         ON `cpev_s`.`attribute_id` = `ea`.`attribute_id`
       LEFT JOIN `catalog_product_entity_varchar` `cpev_0`
              ON `cpev_0`.attribute_id = `cpev_s`.attribute_id
                 AND `cpev_0`.`attribute_id` = `cpev_s`.`attribute_id`
                 AND `cpev_0`.`store_id` = 0
WHERE  `cpev_s`.`value` = 'no_selection'
       AND `ea`.`attribute_code` IN ( 'image', 'small_image', 'thumbnail' )
       AND `cpev_s`.`store_id` > 0
       AND `cpev_s`.`value` != `cpev_0`.`value`
       AND `cpev_s`.`value` = 'no_selection';


-- ======== [ starts duplicate custom optons ] =============
select * from eav_attribute_option_value where
value in (
select distinct  value from eav_attribute_option_value where store_id=0
group by value,option_id having count(value)>1

    )
and store_id=0
order by value,store_id, option_id;
-- ======== [ end duplicate custom optons ] =============

SELECT ea.entity_attribute_id, ea.entity_type_id, ea.attribute_set_id, ea.attribute_group_id, ea.attribute_id, ea.sort_order,
       s.attribute_set_name,
       g.attribute_group_name,
       a.attribute_code,
       a.attribute_id,
       a.frontend_label,
       ea.sort_order
FROM eav_attribute_set s
LEFT JOIN eav_attribute_group g   ON s.attribute_set_id   = g.attribute_set_id
LEFT JOIN eav_entity_attribute ea ON g.attribute_group_id = ea.attribute_group_id
LEFT JOIN eav_attribute a         ON ea.attribute_id      = a.attribute_id
WHERE s.entity_type_id = 4
and g.attribute_group_name='Shipping' and s.attribute_set_name='Migration_sanctuary_lamps' -- in ('Migration_advent_wreaths__candles','shipperhq_shipping_group')
ORDER BY s.attribute_set_name,
         g.sort_order,
         ea.sort_order;

select* from eav_attribute s where s.attribute_code like '%_fee%'
select* from eav_attribute s where s.attribute_code like '%_group'

-- 2895
2898
2899
select * from eav_entity_attribute ea where ea.attribute_id=2902 and attribute_set_id=38
-- TODO eav_entity_attribute

select p.attribute_id,0 as store_id,p.entity_id, eaov.m2_option_id,eaov.m1_option_id
from hqatts p
inner join temp_mar_30_eav_attribute_option_value eaov on p.m1_value=eaov.m1_option_id
where p.attribute_id=1471
-- eaov.m2_option_id=7667 and
      p.entity_id=184798
select * from eav_attribute where  attribute_code='created_at';

select * from rgw_eav_attribute where  attribute_code='created_at';

select count(*) from eav_attribute
create table temp_apr_7_eav_attribute_mapping
select m1.attribute_id as m1_attribute_id ,m2.attribute_id as m2_attribute_id, m1.attribute_code as m1_attribute_code,m2.attribute_code as m2_attribute_code from rgw_eav_attribute m1
inner join eav_attribute m2 on m1.attribute_code=m2.attribute_code
where  m1.attribute_code='created_at';

-- drop table temp_apr_7_eav_attribute_mapping
select * from temp_apr_7_eav_attribute_mapping
where
      m1_attribute_code not in
( select m1_attribute_code from temp_apr_7_eav_attribute_mapping
group by m1_attribute_code having count(*)>1
order by m1_attribute_code)
and
      m1_attribute_id=m2_attribute_id
and m1_attribute_id=1471

create table temp_apr_7_rgw_eav_attribute_modified
select * from rgw_eav_attribute
where
      attribute_code not in
( select m1_attribute_code from temp_apr_7_eav_attribute_mapping
group by m1_attribute_code having count(*)>1
order by m1_attribute_code);

select * from temp_apr_7_rgw_eav_attribute_modified where attribute_id=1465
select * from temp_apr_7_rgw_eav_attribute_modified where attribute_id=1461


select * from temp_apr_7_rgw_eav_attribute_modified m1
where attribute_id not in (
    select attribute_id from rgw_eav_attribute
    )

select * from temp_apr_7_rgw_eav_attribute_modified m1
where attribute_id not in (
    select attribute_id from eav_attribute
    )

create table temp_apr_7_eav_attribute_act_bkp
select * from eav_attribute
select * from temp_apr_7_eav_attribute_act_bkp

--
select attribute_id,entity_type_id, attribute_code, attribute_model, backend_model, backend_type, backend_table, frontend_model, frontend_input, frontend_label, frontend_class, source_model, is_required, is_user_defined, default_value, is_unique, note
from eav_attribute

select
attribute_id,entity_type_id, attribute_code, attribute_model, backend_model, backend_type, backend_table, frontend_model, frontend_input, frontend_label, frontend_class, source_model, is_required, is_user_defined, default_value, is_unique, note
from temp_apr_7_rgw_eav_attribute_modified m1
where attribute_id not in (
    select attribute_id from eav_attribute
    );

select * from rgw_eav_entity_attribute where attribute_id=1471
select * from eav_entity_attribute where attribute_id=2912
select * from hqatts  where attribute_id=1471
# select * from temp_apr_7_rgw_eav_attribute_modified
# where attribute_code in
# ('group_price',
# 'msrp_enabled',
# 'shipperhq_shipping_qty',
# 'shipperhq_additional_price',
# 'shipperhq_carrier_code',
# 'shipperhq_dim_group',
# 'shipperhq_location',
# 'address_valid');
#
# select * from eav_attribute
# where attribute_code in
# ('group_price',
# 'msrp_enabled',
# 'shipperhq_shipping_qty',
# 'shipperhq_additional_price',
# 'shipperhq_carrier_code',
# 'shipperhq_dim_group',
# 'shipperhq_location',
# 'address_valid');

-- m1 m2 code
# 1469	2910	shipperhq_availability_date	shipperhq_availability_date
# 1464	2901	shipperhq_declared_value	shipperhq_declared_value
# 1465	2903	shipperhq_dim_group	shipperhq_dim_group
# 1461	2899	shipperhq_handling_fee	shipperhq_handling_fee
# 1467	2908	shipperhq_malleable_product	shipperhq_malleable_product
# 1468	2909	shipperhq_master_boxes	shipperhq_master_boxes
# 1471	2912	shipperhq_nmfc_class	shipperhq_nmfc_class
# 1473	2913	shipperhq_nmfc_sub	shipperhq_nmfc_sub
# 1466	2907	shipperhq_poss_boxes	shipperhq_poss_boxes
# 1459	2898	shipperhq_shipping_fee	shipperhq_shipping_fee
# 1456	2895	shipperhq_shipping_group	shipperhq_shipping_group
# 1463	2900	shipperhq_volume_weight	shipperhq_volume_weight
# 1457	2896	shipperhq_warehouse	shipperhq_warehouse
# 258	2906	ship_height	ship_height
# 256	2904	ship_length	ship_length
# 254	2902	ship_separately	ship_separately
# 257	2905	ship_width	ship_width



select * from eav_attribute where attribute_code like '%ship_separately%'
select * from eav_attribute where attribute_code like '%ship_length%'

select * from catalog_product_entity_int where attribute_id=1457
select * from rgw_catalog_product_entity_varchar where attribute_id=254

select * from rgw_eav_attribute where attribute_code like '%ship_separately%'; -- 254
select * from rgw_eav_attribute where attribute_code like '%ship_length%'; -- 256

select  rcpei.entity_id from catalog_product_entity_int rcpei where attribute_id=2902
select  rcpei.entity_id from catalog_product_entity_int rcpei where attribute_id=2904

# create table temp_apr_5_catalog_product_entity_int_act_bkp
# select  * from catalog_product_entity_int
#  select * from temp_apr_5_catalog_product_entity_int_act_bkp
-- table : catalog_product_entity_int
# insert into catalog_product_entity_int(attribute_id, store_id, entity_id, value)
 select  2904 as attribute_id, store_id, entity_id, value
from rgw_catalog_product_entity_int a where attribute_id=256
                                        and a.entity_id not in (select  rcpei.entity_id from catalog_product_entity_int rcpei where attribute_id=2904)

-- verification query
    select  count(rcpei.entity_id) from catalog_product_entity_int rcpei where attribute_id=2902
    select  count(rcpei.entity_id) from rgw_catalog_product_entity_int rcpei where attribute_id=254
-- ---------------------------------
-- table : catalog_product_entity_varchar
create table catalog_product_entity_varchar_act_bkp
select  * from catalog_product_entity_varchar
select count(*) from catalog_product_entity_varchar
select count(*) from catalog_product_entity_varchar_act_bkp

insert into catalog_product_entity_varchar(attribute_id, store_id, entity_id, value)
select  2904 as attribute_id, store_id, entity_id, value from rgw_catalog_product_entity_varchar a where attribute_id=256;

select  2904 as attribute_id, store_id, entity_id, value from rgw_catalog_product_entity_varchar a where attribute_id=2904;

-- verification query
    select  count(rcpei.entity_id) from catalog_product_entity_varchar rcpei where attribute_id=2904
    select  count(rcpei.entity_id) from rgw_catalog_product_entity_varchar rcpei where attribute_id=256
-- ---------------------------------

-- table : catalog_product_entity_decimal
create table catalog_product_entity_decimal_act_bkp
select  * from catalog_product_entity_decimal
select count(*) from catalog_product_entity_decimal
select count(*) from catalog_product_entity_decimal_act_bkp

select  2904 as attribute_id, store_id, entity_id, value from rgw_catalog_product_entity_decimal a where attribute_id=256;
select  2904 as attribute_id, store_id, entity_id, value from catalog_product_entity_decimal a where attribute_id=2904;

insert into catalog_product_entity_decimal(attribute_id, store_id, entity_id, value)
select  2904 as attribute_id, store_id, entity_id, value from rgw_catalog_product_entity_decimal a where attribute_id=256;


-- verification query
    select  count(rcpei.entity_id) from catalog_product_entity_decimal rcpei where attribute_id=2904
    select  count(rcpei.entity_id) from rgw_catalog_product_entity_decimal rcpei where attribute_id=256
-- ---------------------------------

-- attribute : ship_width,ship_height
select * from eav_attribute where attribute_code like '%ship_width%'    -- 2905
select * from rgw_eav_attribute where attribute_code like '%ship_width%'; -- 257
select  2905 as attribute_id, store_id, entity_id, value from rgw_catalog_product_entity_decimal a where attribute_id=257;
-- table : catalog_product_entity_decimal

select  2905 as attribute_id, store_id, entity_id, value from rgw_catalog_product_entity_decimal a where attribute_id=257;
select  2905 as attribute_id, store_id, entity_id, value from catalog_product_entity_decimal a where attribute_id=2905;

insert into catalog_product_entity_decimal(attribute_id, store_id, entity_id, value)
select  2905 as attribute_id, store_id, entity_id, value from rgw_catalog_product_entity_decimal a where attribute_id=257;


-- verification query
    select  count(rcpei.entity_id) from catalog_product_entity_decimal rcpei where attribute_id=2905
    select  count(rcpei.entity_id) from rgw_catalog_product_entity_decimal rcpei where attribute_id=257
-- ---------------------------------


select * from eav_attribute where attribute_code like '%ship_height%'   -- 2906
select * from rgw_eav_attribute where attribute_code like '%ship_height%'; -- 258
select  2906 as attribute_id, store_id, entity_id, value from rgw_catalog_product_entity_decimal a where attribute_id=258;
-- table : catalog_product_entity_decimal

select  2906 as attribute_id, store_id, entity_id, value from rgw_catalog_product_entity_decimal a where attribute_id=258;
select  2906 as attribute_id, store_id, entity_id, value from catalog_product_entity_decimal a where attribute_id=2906;

insert into catalog_product_entity_decimal(attribute_id, store_id, entity_id, value)
select  2906 as attribute_id, store_id, entity_id, value from rgw_catalog_product_entity_decimal a where attribute_id=258;


-- verification query
    select  count(rcpei.entity_id) from catalog_product_entity_decimal rcpei where attribute_id=2906
    select  count(rcpei.entity_id) from rgw_catalog_product_entity_decimal rcpei where attribute_id=258
-- ---------------------------------

--  ------------
--  ShipperHQ Dimensional Rule Group
select * from eav_attribute where attribute_code like '%group%'    -- 2903
select * from eav_attribute_option where attribute_id=2903

select * from rgw_eav_attribute where attribute_code like '%group%'    -- 1465
select * from rgw_eav_attribute_option where attribute_id=1465 where attribute_id=1465


