
-- ==============[ Starts TP | Product Related Data: SEO extension attributes are empty ] ================================================
-- task link : https://plumtreeinc.teamwork.com/#/tasks/15550082
/*
INSERT INTO a53979e5_csw_mig.eav_attribute (attribute_id, entity_type_id, attribute_code) VALUES (82, 4, 'meta_title');
INSERT INTO a53979e5_csw_mig.eav_attribute (attribute_id, entity_type_id, attribute_code) VALUES (1491, 4, 'meta_robots');
INSERT INTO a53979e5_csw_mig.eav_attribute (attribute_id, entity_type_id, attribute_code) VALUES (83, 4, 'meta_keyword');
INSERT INTO a53979e5_csw_mig.eav_attribute (attribute_id, entity_type_id, attribute_code) VALUES (84, 4, 'meta_description');
*/
# entity_type_id	entity_type_code
# 1	customer
# 2	customer_address
# 3	catalog_category
# 4	catalog_product
# 5	order
# 6	invoice
# 7	creditmemo
# 8	shipment

# attribute_id	entity_type_id	attribute_code
# 71	        4	            meta_title
# 72	        4	            meta_keyword
# 73	        4	            meta_description
# 176	        4	            meta_robots

select * from tp_eav_entity_type;
select * from tp_eav_attribute where entity_type_id=4 and attribute_code like '%meta_%' order by attribute_id;
select * from tp_eav_attribute where entity_type_id=4 and attribute_code like '%seo_%' order by attribute_id;
select * from tp_eav_attribute where entity_type_id=4 and note like '%MageWorx%';


select * from tp_eav_attribute where entity_type_id=4
                                 and attribute_code in ('meta_title','meta_keyword','meta_description','canonical_url','canonical_cross_domain');




select distinct attribute_id from tp_catalog_product_entity_varchar where attribute_id in (178,177,73,72,71);
select count(*) from tp_catalog_product_entity_varchar where attribute_id in (178,177,73,72,71);

select distinct  attribute_id from tp_catalog_product_entity_varchar where attribute_id in (178,177,73,72,71);

select * from tp_catalog_category_entity_varchar where attribute_id in (178,177,73,72,71);

-- 1226 matched : 1205 and not matched 21 or ye 21 shyd pravin walon ne daly hen
select * from tp_eav_attribute where entity_type_id=4
                                     and attribute_code not in (
    select distinct attribute_code from tp_rgw_eav_attribute where entity_type_id=4 order by attribute_id
    )
-- m1 k seo k attribute to already m2 moojood hen koi ziada gap nh
select * from tp_rgw_eav_attribute where entity_type_id=4
                                     and attribute_code not in (
    select distinct attribute_code from tp_eav_attribute where entity_type_id=4 order by attribute_id
    )
-- ab varcahr check hoga
select * from tp_catalog_product_entity_varchar cpev
where cpev.attribute_id not in
(select distinct  attribute_id from tp_rgw_eav_attribute where entity_type_id=4 and attribute_id in (        select distinct attribute_id from tp_rgw_catalog_product_entity_varchar        ));

select * from tp_rgw_catalog_product_entity_varchar where value like '%worx%';
select * from tp_eav_attribute where entity_type_id=4 and note like '%MageWorx%';
select * from tp_rgw_eav_attribute where entity_type_id=4 and note like '%MageWorx%';
-- MageWorx

# INSERT INTO a53979e5_csw_mig.eav_attribute (attribute_id, entity_type_id, attribute_code, attribute_model, backend_model, backend_type, backend_table, frontend_model, frontend_input, frontend_label, frontend_class, source_model, is_required, is_user_defined, default_value, is_unique, note) VALUES (2887, 4, 'cross_domain_store', null, null, 'int', null, null, 'select', 'Cross Domain Store', null, 'MageWorx\\SeoBase\\Model\\Source\\CrossDomainStore', 0, 0, null, 0, 'This setting was added by MageWorx SEO Suite');
# INSERT INTO a53979e5_csw_mig.eav_attribute (attribute_id, entity_type_id, attribute_code, attribute_model, backend_model, backend_type, backend_table, frontend_model, frontend_input, frontend_label, frontend_class, source_model, is_required, is_user_defined, default_value, is_unique, note) VALUES (2888, 4, 'cross_domain_url', null, null, 'varchar', null, null, 'text', 'Cross Domain URL', 'validate-url', null, 0, 0, null, 0, 'This setting was added by MageWorx SEO Suite');
# INSERT INTO a53979e5_csw_mig.eav_attribute (attribute_id, entity_type_id, attribute_code, attribute_model, backend_model, backend_type, backend_table, frontend_model, frontend_input, frontend_label, frontend_class, source_model, is_required, is_user_defined, default_value, is_unique, note) VALUES (72, 4, 'description', null, null, 'text', null, null, 'textarea', 'Description', null, null, 0, 0, null, 0, 'Note: Switch to a store view level to see the "description" attribute generated by MageWorx templates.');
# INSERT INTO a53979e5_csw_mig.eav_attribute (attribute_id, entity_type_id, attribute_code, attribute_model, backend_model, backend_type, backend_table, frontend_model, frontend_input, frontend_label, frontend_class, source_model, is_required, is_user_defined, default_value, is_unique, note) VALUES (2885, 4, 'in_html_sitemap', null, 'Magento\\Catalog\\Model\\Product\\Attribute\\Backend\\Boolean', 'int', null, null, 'select', 'Include in HTML Sitemap', null, 'Magento\\Eav\\Model\\Entity\\Attribute\\Source\\Boolean', 0, 0, '1', 0, 'This setting was added by MageWorx HTML Sitemap');
# INSERT INTO a53979e5_csw_mig.eav_attribute (attribute_id, entity_type_id, attribute_code, attribute_model, backend_model, backend_type, backend_table, frontend_model, frontend_input, frontend_label, frontend_class, source_model, is_required, is_user_defined, default_value, is_unique, note) VALUES (2891, 4, 'in_xml_sitemap', null, 'Magento\\Catalog\\Model\\Product\\Attribute\\Backend\\Boolean', 'int', null, null, 'select', 'Include in XML Sitemap', null, 'Magento\\Eav\\Model\\Entity\\Attribute\\Source\\Boolean', 0, 0, '1', 0, 'This setting was added by MageWorx XML Sitemap');
# INSERT INTO a53979e5_csw_mig.eav_attribute (attribute_id, entity_type_id, attribute_code, attribute_model, backend_model, backend_type, backend_table, frontend_model, frontend_input, frontend_label, frontend_class, source_model, is_required, is_user_defined, default_value, is_unique, note) VALUES (84, 4, 'meta_description', null, null, 'varchar', null, null, 'textarea', 'Meta Description', null, null, 0, 0, null, 0, 'Note: Switch to a store view level to see the "meta_description" attribute generated by MageWorx templates.');
# INSERT INTO a53979e5_csw_mig.eav_attribute (attribute_id, entity_type_id, attribute_code, attribute_model, backend_model, backend_type, backend_table, frontend_model, frontend_input, frontend_label, frontend_class, source_model, is_required, is_user_defined, default_value, is_unique, note) VALUES (83, 4, 'meta_keyword', null, null, 'text', null, null, 'textarea', 'Meta Keywords', null, null, 0, 0, null, 0, 'Note: Switch to a store view level to see the "meta_keyword" attribute generated by MageWorx templates.');
# INSERT INTO a53979e5_csw_mig.eav_attribute (attribute_id, entity_type_id, attribute_code, attribute_model, backend_model, backend_type, backend_table, frontend_model, frontend_input, frontend_label, frontend_class, source_model, is_required, is_user_defined, default_value, is_unique, note) VALUES (1491, 4, 'meta_robots', null, null, 'varchar', null, null, 'select', 'Meta Robots', null, 'MageWorx\\SeoAll\\Model\\Source\\MetaRobots', 0, 0, null, 0, 'This setting was added by MageWorx SEO Suite');
# INSERT INTO a53979e5_csw_mig.eav_attribute (attribute_id, entity_type_id, attribute_code, attribute_model, backend_model, backend_type, backend_table, frontend_model, frontend_input, frontend_label, frontend_class, source_model, is_required, is_user_defined, default_value, is_unique, note) VALUES (82, 4, 'meta_title', null, null, 'varchar', null, null, 'text', 'Meta Title', null, null, 0, 0, null, 0, 'Note: Switch to a store view level to see the "meta_title" attribute generated by MageWorx templates.');
# INSERT INTO a53979e5_csw_mig.eav_attribute (attribute_id, entity_type_id, attribute_code, attribute_model, backend_model, backend_type, backend_table, frontend_model, frontend_input, frontend_label, frontend_class, source_model, is_required, is_user_defined, default_value, is_unique, note) VALUES (1497, 4, 'product_seo_name', null, null, 'varchar', null, null, 'text', 'SEO Name', null, null, 0, 0, null, 0, 'Note: Switch to a store view level to see the "product_seo_name" attribute generated by MageWorx templates.');
# INSERT INTO a53979e5_csw_mig.eav_attribute (attribute_id, entity_type_id, attribute_code, attribute_model, backend_model, backend_type, backend_table, frontend_model, frontend_input, frontend_label, frontend_class, source_model, is_required, is_user_defined, default_value, is_unique, note) VALUES (73, 4, 'short_description', null, null, 'text', null, null, 'textarea', 'Short Description', null, null, 0, 0, null, 0, 'Note: Switch to a store view level to see the "short_description" attribute generated by MageWorx templates.');
# INSERT INTO a53979e5_csw_mig.eav_attribute (attribute_id, entity_type_id, attribute_code, attribute_model, backend_model, backend_type, backend_table, frontend_model, frontend_input, frontend_label, frontend_class, source_model, is_required, is_user_defined, default_value, is_unique, note) VALUES (97, 4, 'url_key', null, null, 'varchar', null, null, 'text', 'URL Key', null, null, 0, 0, null, 0, 'Note: Switch to a store view level to see the "url_key" attribute generated by MageWorx templates.');
# INSERT INTO a53979e5_csw_mig.eav_attribute (attribute_id, entity_type_id, attribute_code, attribute_model, backend_model, backend_type, backend_table, frontend_model, frontend_input, frontend_label, frontend_class, source_model, is_required, is_user_defined, default_value, is_unique, note) VALUES (2889, 4, 'use_in_crosslinking', null, 'Magento\\Catalog\\Model\\Product\\Attribute\\Backend\\Boolean', 'int', null, null, 'select', 'Use in Cross Linking', null, 'Magento\\Eav\\Model\\Entity\\Attribute\\Source\\Boolean', 0, 0, '1', 0, 'This setting was added by MageWorx SEO Cross Links');

-- ==============[ Ends TP | Product Related Data: SEO extension attributes are empty ] ================================================
